//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultipleChoiceApp.Bi.Exam {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExamOverview", Namespace="http://peteranh.com/Services/Exam")]
    [System.SerializableAttribute()]
    public partial class ExamOverview : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int TakenStudentCountField;
        
        private double AveragePointsField;
        
        private int DurationField;
        
        private int TotalQuestionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TakenStudentCount {
            get {
                return this.TakenStudentCountField;
            }
            set {
                if ((this.TakenStudentCountField.Equals(value) != true)) {
                    this.TakenStudentCountField = value;
                    this.RaisePropertyChanged("TakenStudentCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public double AveragePoints {
            get {
                return this.AveragePointsField;
            }
            set {
                if ((this.AveragePointsField.Equals(value) != true)) {
                    this.AveragePointsField = value;
                    this.RaisePropertyChanged("AveragePoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int TotalQuestion {
            get {
                return this.TotalQuestionField;
            }
            set {
                if ((this.TotalQuestionField.Equals(value) != true)) {
                    this.TotalQuestionField = value;
                    this.RaisePropertyChanged("TotalQuestion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Exam", Namespace="http://peteranh.com/Services/Exam")]
    [System.SerializableAttribute()]
    public partial class Exam : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private int SemesterField;
        
        private int SubjectIdField;
        
        private System.DateTime StartAtField;
        
        private System.DateTime EndAtField;
        
        private int EasyQtyField;
        
        private int HardQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectCodeField;
        
        private int TotalQuestionField;
        
        private int StudentCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MultipleChoiceApp.Bi.Exam.Subject SubjectField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Semester {
            get {
                return this.SemesterField;
            }
            set {
                if ((this.SemesterField.Equals(value) != true)) {
                    this.SemesterField = value;
                    this.RaisePropertyChanged("Semester");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SubjectId {
            get {
                return this.SubjectIdField;
            }
            set {
                if ((this.SubjectIdField.Equals(value) != true)) {
                    this.SubjectIdField = value;
                    this.RaisePropertyChanged("SubjectId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime StartAt {
            get {
                return this.StartAtField;
            }
            set {
                if ((this.StartAtField.Equals(value) != true)) {
                    this.StartAtField = value;
                    this.RaisePropertyChanged("StartAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime EndAt {
            get {
                return this.EndAtField;
            }
            set {
                if ((this.EndAtField.Equals(value) != true)) {
                    this.EndAtField = value;
                    this.RaisePropertyChanged("EndAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int EasyQty {
            get {
                return this.EasyQtyField;
            }
            set {
                if ((this.EasyQtyField.Equals(value) != true)) {
                    this.EasyQtyField = value;
                    this.RaisePropertyChanged("EasyQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int HardQty {
            get {
                return this.HardQtyField;
            }
            set {
                if ((this.HardQtyField.Equals(value) != true)) {
                    this.HardQtyField = value;
                    this.RaisePropertyChanged("HardQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string SubjectCode {
            get {
                return this.SubjectCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectCodeField, value) != true)) {
                    this.SubjectCodeField = value;
                    this.RaisePropertyChanged("SubjectCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int TotalQuestion {
            get {
                return this.TotalQuestionField;
            }
            set {
                if ((this.TotalQuestionField.Equals(value) != true)) {
                    this.TotalQuestionField = value;
                    this.RaisePropertyChanged("TotalQuestion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int StudentCount {
            get {
                return this.StudentCountField;
            }
            set {
                if ((this.StudentCountField.Equals(value) != true)) {
                    this.StudentCountField = value;
                    this.RaisePropertyChanged("StudentCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public MultipleChoiceApp.Bi.Exam.Subject Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Subject", Namespace="http://peteranh.com/Services/Exam")]
    [System.SerializableAttribute()]
    public partial class Subject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private int TotalQuestionField;
        
        private int DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LecturerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int TotalQuestion {
            get {
                return this.TotalQuestionField;
            }
            set {
                if ((this.TotalQuestionField.Equals(value) != true)) {
                    this.TotalQuestionField = value;
                    this.RaisePropertyChanged("TotalQuestion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Lecturer {
            get {
                return this.LecturerField;
            }
            set {
                if ((object.ReferenceEquals(this.LecturerField, value) != true)) {
                    this.LecturerField = value;
                    this.RaisePropertyChanged("Lecturer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://peteranh.com/Services/Exam", ConfigurationName="Bi.Exam.ExamServiceSoap")]
    public interface ExamServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Exam/isAvailableBetweenDate", ReplyAction="*")]
        bool isAvailableBetweenDate(System.DateTime start, System.DateTime end, int subjectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Exam/isAvailableBetweenDate", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> isAvailableBetweenDateAsync(System.DateTime start, System.DateTime end, int subjectId);
        
        // CODEGEN: Generating message contract since element name getExamOverviewByIdResult from namespace http://peteranh.com/Services/Exam is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Exam/getExamOverviewById", ReplyAction="*")]
        MultipleChoiceApp.Bi.Exam.getExamOverviewByIdResponse getExamOverviewById(MultipleChoiceApp.Bi.Exam.getExamOverviewByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Exam/getExamOverviewById", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Exam.getExamOverviewByIdResponse> getExamOverviewByIdAsync(MultipleChoiceApp.Bi.Exam.getExamOverviewByIdRequest request);
        
        // CODEGEN: Generating message contract since element name getAllForReportResult from namespace http://peteranh.com/Services/Exam is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Exam/getAllForReport", ReplyAction="*")]
        MultipleChoiceApp.Bi.Exam.getAllForReportResponse getAllForReport(MultipleChoiceApp.Bi.Exam.getAllForReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Exam/getAllForReport", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Exam.getAllForReportResponse> getAllForReportAsync(MultipleChoiceApp.Bi.Exam.getAllForReportRequest request);
        
        // CODEGEN: Generating message contract since element name getExamReportByIdResult from namespace http://peteranh.com/Services/Exam is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Exam/getExamReportById", ReplyAction="*")]
        MultipleChoiceApp.Bi.Exam.getExamReportByIdResponse getExamReportById(MultipleChoiceApp.Bi.Exam.getExamReportByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Exam/getExamReportById", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Exam.getExamReportByIdResponse> getExamReportByIdAsync(MultipleChoiceApp.Bi.Exam.getExamReportByIdRequest request);
        
        // CODEGEN: Generating message contract since element name getAvailableBySubjectIdResult from namespace http://peteranh.com/Services/Exam is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Exam/getAvailableBySubjectId", ReplyAction="*")]
        MultipleChoiceApp.Bi.Exam.getAvailableBySubjectIdResponse getAvailableBySubjectId(MultipleChoiceApp.Bi.Exam.getAvailableBySubjectIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Exam/getAvailableBySubjectId", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Exam.getAvailableBySubjectIdResponse> getAvailableBySubjectIdAsync(MultipleChoiceApp.Bi.Exam.getAvailableBySubjectIdRequest request);
        
        // CODEGEN: Generating message contract since element name keyword from namespace http://peteranh.com/Services/Exam is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Exam/searchByKeyword", ReplyAction="*")]
        MultipleChoiceApp.Bi.Exam.searchByKeywordResponse searchByKeyword(MultipleChoiceApp.Bi.Exam.searchByKeywordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Exam/searchByKeyword", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Exam.searchByKeywordResponse> searchByKeywordAsync(MultipleChoiceApp.Bi.Exam.searchByKeywordRequest request);
        
        // CODEGEN: Generating message contract since element name getAllForSelectDataResult from namespace http://peteranh.com/Services/Exam is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Exam/getAllForSelectData", ReplyAction="*")]
        MultipleChoiceApp.Bi.Exam.getAllForSelectDataResponse getAllForSelectData(MultipleChoiceApp.Bi.Exam.getAllForSelectDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Exam/getAllForSelectData", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Exam.getAllForSelectDataResponse> getAllForSelectDataAsync(MultipleChoiceApp.Bi.Exam.getAllForSelectDataRequest request);
        
        // CODEGEN: Generating message contract since element name getAllResult from namespace http://peteranh.com/Services/Exam is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Exam/getAll", ReplyAction="*")]
        MultipleChoiceApp.Bi.Exam.getAllResponse getAll(MultipleChoiceApp.Bi.Exam.getAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Exam/getAll", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Exam.getAllResponse> getAllAsync(MultipleChoiceApp.Bi.Exam.getAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Exam/countAll", ReplyAction="*")]
        int countAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Exam/countAll", ReplyAction="*")]
        System.Threading.Tasks.Task<int> countAllAsync();
        
        // CODEGEN: Generating message contract since element name getDetailsByIdResult from namespace http://peteranh.com/Services/Exam is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Exam/getDetailsById", ReplyAction="*")]
        MultipleChoiceApp.Bi.Exam.getDetailsByIdResponse getDetailsById(MultipleChoiceApp.Bi.Exam.getDetailsByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Exam/getDetailsById", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Exam.getDetailsByIdResponse> getDetailsByIdAsync(MultipleChoiceApp.Bi.Exam.getDetailsByIdRequest request);
        
        // CODEGEN: Generating message contract since element name item from namespace http://peteranh.com/Services/Exam is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Exam/add", ReplyAction="*")]
        MultipleChoiceApp.Bi.Exam.addResponse add(MultipleChoiceApp.Bi.Exam.addRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Exam/add", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Exam.addResponse> addAsync(MultipleChoiceApp.Bi.Exam.addRequest request);
        
        // CODEGEN: Generating message contract since element name list from namespace http://peteranh.com/Services/Exam is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Exam/addMany", ReplyAction="*")]
        MultipleChoiceApp.Bi.Exam.addManyResponse addMany(MultipleChoiceApp.Bi.Exam.addManyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Exam/addMany", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Exam.addManyResponse> addManyAsync(MultipleChoiceApp.Bi.Exam.addManyRequest request);
        
        // CODEGEN: Generating message contract since element name item from namespace http://peteranh.com/Services/Exam is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Exam/update", ReplyAction="*")]
        MultipleChoiceApp.Bi.Exam.updateResponse update(MultipleChoiceApp.Bi.Exam.updateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Exam/update", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Exam.updateResponse> updateAsync(MultipleChoiceApp.Bi.Exam.updateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Exam/delete", ReplyAction="*")]
        bool delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Exam/delete", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> deleteAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getExamOverviewByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getExamOverviewById", Namespace="http://peteranh.com/Services/Exam", Order=0)]
        public MultipleChoiceApp.Bi.Exam.getExamOverviewByIdRequestBody Body;
        
        public getExamOverviewByIdRequest() {
        }
        
        public getExamOverviewByIdRequest(MultipleChoiceApp.Bi.Exam.getExamOverviewByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Exam")]
    public partial class getExamOverviewByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public getExamOverviewByIdRequestBody() {
        }
        
        public getExamOverviewByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getExamOverviewByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getExamOverviewByIdResponse", Namespace="http://peteranh.com/Services/Exam", Order=0)]
        public MultipleChoiceApp.Bi.Exam.getExamOverviewByIdResponseBody Body;
        
        public getExamOverviewByIdResponse() {
        }
        
        public getExamOverviewByIdResponse(MultipleChoiceApp.Bi.Exam.getExamOverviewByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Exam")]
    public partial class getExamOverviewByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MultipleChoiceApp.Bi.Exam.ExamOverview getExamOverviewByIdResult;
        
        public getExamOverviewByIdResponseBody() {
        }
        
        public getExamOverviewByIdResponseBody(MultipleChoiceApp.Bi.Exam.ExamOverview getExamOverviewByIdResult) {
            this.getExamOverviewByIdResult = getExamOverviewByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllForReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllForReport", Namespace="http://peteranh.com/Services/Exam", Order=0)]
        public MultipleChoiceApp.Bi.Exam.getAllForReportRequestBody Body;
        
        public getAllForReportRequest() {
        }
        
        public getAllForReportRequest(MultipleChoiceApp.Bi.Exam.getAllForReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getAllForReportRequestBody {
        
        public getAllForReportRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllForReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllForReportResponse", Namespace="http://peteranh.com/Services/Exam", Order=0)]
        public MultipleChoiceApp.Bi.Exam.getAllForReportResponseBody Body;
        
        public getAllForReportResponse() {
        }
        
        public getAllForReportResponse(MultipleChoiceApp.Bi.Exam.getAllForReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Exam")]
    public partial class getAllForReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Exam.Exam> getAllForReportResult;
        
        public getAllForReportResponseBody() {
        }
        
        public getAllForReportResponseBody(System.Collections.Generic.List<MultipleChoiceApp.Bi.Exam.Exam> getAllForReportResult) {
            this.getAllForReportResult = getAllForReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getExamReportByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getExamReportById", Namespace="http://peteranh.com/Services/Exam", Order=0)]
        public MultipleChoiceApp.Bi.Exam.getExamReportByIdRequestBody Body;
        
        public getExamReportByIdRequest() {
        }
        
        public getExamReportByIdRequest(MultipleChoiceApp.Bi.Exam.getExamReportByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Exam")]
    public partial class getExamReportByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public getExamReportByIdRequestBody() {
        }
        
        public getExamReportByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getExamReportByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getExamReportByIdResponse", Namespace="http://peteranh.com/Services/Exam", Order=0)]
        public MultipleChoiceApp.Bi.Exam.getExamReportByIdResponseBody Body;
        
        public getExamReportByIdResponse() {
        }
        
        public getExamReportByIdResponse(MultipleChoiceApp.Bi.Exam.getExamReportByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Exam")]
    public partial class getExamReportByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MultipleChoiceApp.Bi.Exam.Exam getExamReportByIdResult;
        
        public getExamReportByIdResponseBody() {
        }
        
        public getExamReportByIdResponseBody(MultipleChoiceApp.Bi.Exam.Exam getExamReportByIdResult) {
            this.getExamReportByIdResult = getExamReportByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAvailableBySubjectIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAvailableBySubjectId", Namespace="http://peteranh.com/Services/Exam", Order=0)]
        public MultipleChoiceApp.Bi.Exam.getAvailableBySubjectIdRequestBody Body;
        
        public getAvailableBySubjectIdRequest() {
        }
        
        public getAvailableBySubjectIdRequest(MultipleChoiceApp.Bi.Exam.getAvailableBySubjectIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Exam")]
    public partial class getAvailableBySubjectIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SubjectId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime d;
        
        public getAvailableBySubjectIdRequestBody() {
        }
        
        public getAvailableBySubjectIdRequestBody(int SubjectId, System.DateTime d) {
            this.SubjectId = SubjectId;
            this.d = d;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAvailableBySubjectIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAvailableBySubjectIdResponse", Namespace="http://peteranh.com/Services/Exam", Order=0)]
        public MultipleChoiceApp.Bi.Exam.getAvailableBySubjectIdResponseBody Body;
        
        public getAvailableBySubjectIdResponse() {
        }
        
        public getAvailableBySubjectIdResponse(MultipleChoiceApp.Bi.Exam.getAvailableBySubjectIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Exam")]
    public partial class getAvailableBySubjectIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MultipleChoiceApp.Bi.Exam.Exam getAvailableBySubjectIdResult;
        
        public getAvailableBySubjectIdResponseBody() {
        }
        
        public getAvailableBySubjectIdResponseBody(MultipleChoiceApp.Bi.Exam.Exam getAvailableBySubjectIdResult) {
            this.getAvailableBySubjectIdResult = getAvailableBySubjectIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchByKeywordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchByKeyword", Namespace="http://peteranh.com/Services/Exam", Order=0)]
        public MultipleChoiceApp.Bi.Exam.searchByKeywordRequestBody Body;
        
        public searchByKeywordRequest() {
        }
        
        public searchByKeywordRequest(MultipleChoiceApp.Bi.Exam.searchByKeywordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Exam")]
    public partial class searchByKeywordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string keyword;
        
        public searchByKeywordRequestBody() {
        }
        
        public searchByKeywordRequestBody(string keyword) {
            this.keyword = keyword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchByKeywordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchByKeywordResponse", Namespace="http://peteranh.com/Services/Exam", Order=0)]
        public MultipleChoiceApp.Bi.Exam.searchByKeywordResponseBody Body;
        
        public searchByKeywordResponse() {
        }
        
        public searchByKeywordResponse(MultipleChoiceApp.Bi.Exam.searchByKeywordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Exam")]
    public partial class searchByKeywordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Exam.Exam> searchByKeywordResult;
        
        public searchByKeywordResponseBody() {
        }
        
        public searchByKeywordResponseBody(System.Collections.Generic.List<MultipleChoiceApp.Bi.Exam.Exam> searchByKeywordResult) {
            this.searchByKeywordResult = searchByKeywordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllForSelectDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllForSelectData", Namespace="http://peteranh.com/Services/Exam", Order=0)]
        public MultipleChoiceApp.Bi.Exam.getAllForSelectDataRequestBody Body;
        
        public getAllForSelectDataRequest() {
        }
        
        public getAllForSelectDataRequest(MultipleChoiceApp.Bi.Exam.getAllForSelectDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getAllForSelectDataRequestBody {
        
        public getAllForSelectDataRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllForSelectDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllForSelectDataResponse", Namespace="http://peteranh.com/Services/Exam", Order=0)]
        public MultipleChoiceApp.Bi.Exam.getAllForSelectDataResponseBody Body;
        
        public getAllForSelectDataResponse() {
        }
        
        public getAllForSelectDataResponse(MultipleChoiceApp.Bi.Exam.getAllForSelectDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Exam")]
    public partial class getAllForSelectDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Exam.Exam> getAllForSelectDataResult;
        
        public getAllForSelectDataResponseBody() {
        }
        
        public getAllForSelectDataResponseBody(System.Collections.Generic.List<MultipleChoiceApp.Bi.Exam.Exam> getAllForSelectDataResult) {
            this.getAllForSelectDataResult = getAllForSelectDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAll", Namespace="http://peteranh.com/Services/Exam", Order=0)]
        public MultipleChoiceApp.Bi.Exam.getAllRequestBody Body;
        
        public getAllRequest() {
        }
        
        public getAllRequest(MultipleChoiceApp.Bi.Exam.getAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Exam")]
    public partial class getAllRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int itemsPerPage;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int currentPage;
        
        public getAllRequestBody() {
        }
        
        public getAllRequestBody(int itemsPerPage, int currentPage) {
            this.itemsPerPage = itemsPerPage;
            this.currentPage = currentPage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllResponse", Namespace="http://peteranh.com/Services/Exam", Order=0)]
        public MultipleChoiceApp.Bi.Exam.getAllResponseBody Body;
        
        public getAllResponse() {
        }
        
        public getAllResponse(MultipleChoiceApp.Bi.Exam.getAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Exam")]
    public partial class getAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Exam.Exam> getAllResult;
        
        public getAllResponseBody() {
        }
        
        public getAllResponseBody(System.Collections.Generic.List<MultipleChoiceApp.Bi.Exam.Exam> getAllResult) {
            this.getAllResult = getAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDetailsByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDetailsById", Namespace="http://peteranh.com/Services/Exam", Order=0)]
        public MultipleChoiceApp.Bi.Exam.getDetailsByIdRequestBody Body;
        
        public getDetailsByIdRequest() {
        }
        
        public getDetailsByIdRequest(MultipleChoiceApp.Bi.Exam.getDetailsByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Exam")]
    public partial class getDetailsByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public getDetailsByIdRequestBody() {
        }
        
        public getDetailsByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDetailsByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDetailsByIdResponse", Namespace="http://peteranh.com/Services/Exam", Order=0)]
        public MultipleChoiceApp.Bi.Exam.getDetailsByIdResponseBody Body;
        
        public getDetailsByIdResponse() {
        }
        
        public getDetailsByIdResponse(MultipleChoiceApp.Bi.Exam.getDetailsByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Exam")]
    public partial class getDetailsByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MultipleChoiceApp.Bi.Exam.Exam getDetailsByIdResult;
        
        public getDetailsByIdResponseBody() {
        }
        
        public getDetailsByIdResponseBody(MultipleChoiceApp.Bi.Exam.Exam getDetailsByIdResult) {
            this.getDetailsByIdResult = getDetailsByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="add", Namespace="http://peteranh.com/Services/Exam", Order=0)]
        public MultipleChoiceApp.Bi.Exam.addRequestBody Body;
        
        public addRequest() {
        }
        
        public addRequest(MultipleChoiceApp.Bi.Exam.addRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Exam")]
    public partial class addRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MultipleChoiceApp.Bi.Exam.Exam item;
        
        public addRequestBody() {
        }
        
        public addRequestBody(MultipleChoiceApp.Bi.Exam.Exam item) {
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addResponse", Namespace="http://peteranh.com/Services/Exam", Order=0)]
        public MultipleChoiceApp.Bi.Exam.addResponseBody Body;
        
        public addResponse() {
        }
        
        public addResponse(MultipleChoiceApp.Bi.Exam.addResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Exam")]
    public partial class addResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool addResult;
        
        public addResponseBody() {
        }
        
        public addResponseBody(bool addResult) {
            this.addResult = addResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addManyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addMany", Namespace="http://peteranh.com/Services/Exam", Order=0)]
        public MultipleChoiceApp.Bi.Exam.addManyRequestBody Body;
        
        public addManyRequest() {
        }
        
        public addManyRequest(MultipleChoiceApp.Bi.Exam.addManyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Exam")]
    public partial class addManyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Exam.Exam> list;
        
        public addManyRequestBody() {
        }
        
        public addManyRequestBody(System.Collections.Generic.List<MultipleChoiceApp.Bi.Exam.Exam> list) {
            this.list = list;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addManyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addManyResponse", Namespace="http://peteranh.com/Services/Exam", Order=0)]
        public MultipleChoiceApp.Bi.Exam.addManyResponseBody Body;
        
        public addManyResponse() {
        }
        
        public addManyResponse(MultipleChoiceApp.Bi.Exam.addManyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Exam")]
    public partial class addManyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int addManyResult;
        
        public addManyResponseBody() {
        }
        
        public addManyResponseBody(int addManyResult) {
            this.addManyResult = addManyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="update", Namespace="http://peteranh.com/Services/Exam", Order=0)]
        public MultipleChoiceApp.Bi.Exam.updateRequestBody Body;
        
        public updateRequest() {
        }
        
        public updateRequest(MultipleChoiceApp.Bi.Exam.updateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Exam")]
    public partial class updateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MultipleChoiceApp.Bi.Exam.Exam item;
        
        public updateRequestBody() {
        }
        
        public updateRequestBody(MultipleChoiceApp.Bi.Exam.Exam item) {
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateResponse", Namespace="http://peteranh.com/Services/Exam", Order=0)]
        public MultipleChoiceApp.Bi.Exam.updateResponseBody Body;
        
        public updateResponse() {
        }
        
        public updateResponse(MultipleChoiceApp.Bi.Exam.updateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Exam")]
    public partial class updateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool updateResult;
        
        public updateResponseBody() {
        }
        
        public updateResponseBody(bool updateResult) {
            this.updateResult = updateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExamServiceSoapChannel : MultipleChoiceApp.Bi.Exam.ExamServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExamServiceSoapClient : System.ServiceModel.ClientBase<MultipleChoiceApp.Bi.Exam.ExamServiceSoap>, MultipleChoiceApp.Bi.Exam.ExamServiceSoap {
        
        public ExamServiceSoapClient() {
        }
        
        public ExamServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExamServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExamServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExamServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool isAvailableBetweenDate(System.DateTime start, System.DateTime end, int subjectId) {
            return base.Channel.isAvailableBetweenDate(start, end, subjectId);
        }
        
        public System.Threading.Tasks.Task<bool> isAvailableBetweenDateAsync(System.DateTime start, System.DateTime end, int subjectId) {
            return base.Channel.isAvailableBetweenDateAsync(start, end, subjectId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Exam.getExamOverviewByIdResponse MultipleChoiceApp.Bi.Exam.ExamServiceSoap.getExamOverviewById(MultipleChoiceApp.Bi.Exam.getExamOverviewByIdRequest request) {
            return base.Channel.getExamOverviewById(request);
        }
        
        public MultipleChoiceApp.Bi.Exam.ExamOverview getExamOverviewById(int id) {
            MultipleChoiceApp.Bi.Exam.getExamOverviewByIdRequest inValue = new MultipleChoiceApp.Bi.Exam.getExamOverviewByIdRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Exam.getExamOverviewByIdRequestBody();
            inValue.Body.id = id;
            MultipleChoiceApp.Bi.Exam.getExamOverviewByIdResponse retVal = ((MultipleChoiceApp.Bi.Exam.ExamServiceSoap)(this)).getExamOverviewById(inValue);
            return retVal.Body.getExamOverviewByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Exam.getExamOverviewByIdResponse> MultipleChoiceApp.Bi.Exam.ExamServiceSoap.getExamOverviewByIdAsync(MultipleChoiceApp.Bi.Exam.getExamOverviewByIdRequest request) {
            return base.Channel.getExamOverviewByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Exam.getExamOverviewByIdResponse> getExamOverviewByIdAsync(int id) {
            MultipleChoiceApp.Bi.Exam.getExamOverviewByIdRequest inValue = new MultipleChoiceApp.Bi.Exam.getExamOverviewByIdRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Exam.getExamOverviewByIdRequestBody();
            inValue.Body.id = id;
            return ((MultipleChoiceApp.Bi.Exam.ExamServiceSoap)(this)).getExamOverviewByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Exam.getAllForReportResponse MultipleChoiceApp.Bi.Exam.ExamServiceSoap.getAllForReport(MultipleChoiceApp.Bi.Exam.getAllForReportRequest request) {
            return base.Channel.getAllForReport(request);
        }
        
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Exam.Exam> getAllForReport() {
            MultipleChoiceApp.Bi.Exam.getAllForReportRequest inValue = new MultipleChoiceApp.Bi.Exam.getAllForReportRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Exam.getAllForReportRequestBody();
            MultipleChoiceApp.Bi.Exam.getAllForReportResponse retVal = ((MultipleChoiceApp.Bi.Exam.ExamServiceSoap)(this)).getAllForReport(inValue);
            return retVal.Body.getAllForReportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Exam.getAllForReportResponse> MultipleChoiceApp.Bi.Exam.ExamServiceSoap.getAllForReportAsync(MultipleChoiceApp.Bi.Exam.getAllForReportRequest request) {
            return base.Channel.getAllForReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Exam.getAllForReportResponse> getAllForReportAsync() {
            MultipleChoiceApp.Bi.Exam.getAllForReportRequest inValue = new MultipleChoiceApp.Bi.Exam.getAllForReportRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Exam.getAllForReportRequestBody();
            return ((MultipleChoiceApp.Bi.Exam.ExamServiceSoap)(this)).getAllForReportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Exam.getExamReportByIdResponse MultipleChoiceApp.Bi.Exam.ExamServiceSoap.getExamReportById(MultipleChoiceApp.Bi.Exam.getExamReportByIdRequest request) {
            return base.Channel.getExamReportById(request);
        }
        
        public MultipleChoiceApp.Bi.Exam.Exam getExamReportById(int id) {
            MultipleChoiceApp.Bi.Exam.getExamReportByIdRequest inValue = new MultipleChoiceApp.Bi.Exam.getExamReportByIdRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Exam.getExamReportByIdRequestBody();
            inValue.Body.id = id;
            MultipleChoiceApp.Bi.Exam.getExamReportByIdResponse retVal = ((MultipleChoiceApp.Bi.Exam.ExamServiceSoap)(this)).getExamReportById(inValue);
            return retVal.Body.getExamReportByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Exam.getExamReportByIdResponse> MultipleChoiceApp.Bi.Exam.ExamServiceSoap.getExamReportByIdAsync(MultipleChoiceApp.Bi.Exam.getExamReportByIdRequest request) {
            return base.Channel.getExamReportByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Exam.getExamReportByIdResponse> getExamReportByIdAsync(int id) {
            MultipleChoiceApp.Bi.Exam.getExamReportByIdRequest inValue = new MultipleChoiceApp.Bi.Exam.getExamReportByIdRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Exam.getExamReportByIdRequestBody();
            inValue.Body.id = id;
            return ((MultipleChoiceApp.Bi.Exam.ExamServiceSoap)(this)).getExamReportByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Exam.getAvailableBySubjectIdResponse MultipleChoiceApp.Bi.Exam.ExamServiceSoap.getAvailableBySubjectId(MultipleChoiceApp.Bi.Exam.getAvailableBySubjectIdRequest request) {
            return base.Channel.getAvailableBySubjectId(request);
        }
        
        public MultipleChoiceApp.Bi.Exam.Exam getAvailableBySubjectId(int SubjectId, System.DateTime d) {
            MultipleChoiceApp.Bi.Exam.getAvailableBySubjectIdRequest inValue = new MultipleChoiceApp.Bi.Exam.getAvailableBySubjectIdRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Exam.getAvailableBySubjectIdRequestBody();
            inValue.Body.SubjectId = SubjectId;
            inValue.Body.d = d;
            MultipleChoiceApp.Bi.Exam.getAvailableBySubjectIdResponse retVal = ((MultipleChoiceApp.Bi.Exam.ExamServiceSoap)(this)).getAvailableBySubjectId(inValue);
            return retVal.Body.getAvailableBySubjectIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Exam.getAvailableBySubjectIdResponse> MultipleChoiceApp.Bi.Exam.ExamServiceSoap.getAvailableBySubjectIdAsync(MultipleChoiceApp.Bi.Exam.getAvailableBySubjectIdRequest request) {
            return base.Channel.getAvailableBySubjectIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Exam.getAvailableBySubjectIdResponse> getAvailableBySubjectIdAsync(int SubjectId, System.DateTime d) {
            MultipleChoiceApp.Bi.Exam.getAvailableBySubjectIdRequest inValue = new MultipleChoiceApp.Bi.Exam.getAvailableBySubjectIdRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Exam.getAvailableBySubjectIdRequestBody();
            inValue.Body.SubjectId = SubjectId;
            inValue.Body.d = d;
            return ((MultipleChoiceApp.Bi.Exam.ExamServiceSoap)(this)).getAvailableBySubjectIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Exam.searchByKeywordResponse MultipleChoiceApp.Bi.Exam.ExamServiceSoap.searchByKeyword(MultipleChoiceApp.Bi.Exam.searchByKeywordRequest request) {
            return base.Channel.searchByKeyword(request);
        }
        
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Exam.Exam> searchByKeyword(string keyword) {
            MultipleChoiceApp.Bi.Exam.searchByKeywordRequest inValue = new MultipleChoiceApp.Bi.Exam.searchByKeywordRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Exam.searchByKeywordRequestBody();
            inValue.Body.keyword = keyword;
            MultipleChoiceApp.Bi.Exam.searchByKeywordResponse retVal = ((MultipleChoiceApp.Bi.Exam.ExamServiceSoap)(this)).searchByKeyword(inValue);
            return retVal.Body.searchByKeywordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Exam.searchByKeywordResponse> MultipleChoiceApp.Bi.Exam.ExamServiceSoap.searchByKeywordAsync(MultipleChoiceApp.Bi.Exam.searchByKeywordRequest request) {
            return base.Channel.searchByKeywordAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Exam.searchByKeywordResponse> searchByKeywordAsync(string keyword) {
            MultipleChoiceApp.Bi.Exam.searchByKeywordRequest inValue = new MultipleChoiceApp.Bi.Exam.searchByKeywordRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Exam.searchByKeywordRequestBody();
            inValue.Body.keyword = keyword;
            return ((MultipleChoiceApp.Bi.Exam.ExamServiceSoap)(this)).searchByKeywordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Exam.getAllForSelectDataResponse MultipleChoiceApp.Bi.Exam.ExamServiceSoap.getAllForSelectData(MultipleChoiceApp.Bi.Exam.getAllForSelectDataRequest request) {
            return base.Channel.getAllForSelectData(request);
        }
        
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Exam.Exam> getAllForSelectData() {
            MultipleChoiceApp.Bi.Exam.getAllForSelectDataRequest inValue = new MultipleChoiceApp.Bi.Exam.getAllForSelectDataRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Exam.getAllForSelectDataRequestBody();
            MultipleChoiceApp.Bi.Exam.getAllForSelectDataResponse retVal = ((MultipleChoiceApp.Bi.Exam.ExamServiceSoap)(this)).getAllForSelectData(inValue);
            return retVal.Body.getAllForSelectDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Exam.getAllForSelectDataResponse> MultipleChoiceApp.Bi.Exam.ExamServiceSoap.getAllForSelectDataAsync(MultipleChoiceApp.Bi.Exam.getAllForSelectDataRequest request) {
            return base.Channel.getAllForSelectDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Exam.getAllForSelectDataResponse> getAllForSelectDataAsync() {
            MultipleChoiceApp.Bi.Exam.getAllForSelectDataRequest inValue = new MultipleChoiceApp.Bi.Exam.getAllForSelectDataRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Exam.getAllForSelectDataRequestBody();
            return ((MultipleChoiceApp.Bi.Exam.ExamServiceSoap)(this)).getAllForSelectDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Exam.getAllResponse MultipleChoiceApp.Bi.Exam.ExamServiceSoap.getAll(MultipleChoiceApp.Bi.Exam.getAllRequest request) {
            return base.Channel.getAll(request);
        }
        
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Exam.Exam> getAll(int itemsPerPage, int currentPage) {
            MultipleChoiceApp.Bi.Exam.getAllRequest inValue = new MultipleChoiceApp.Bi.Exam.getAllRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Exam.getAllRequestBody();
            inValue.Body.itemsPerPage = itemsPerPage;
            inValue.Body.currentPage = currentPage;
            MultipleChoiceApp.Bi.Exam.getAllResponse retVal = ((MultipleChoiceApp.Bi.Exam.ExamServiceSoap)(this)).getAll(inValue);
            return retVal.Body.getAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Exam.getAllResponse> MultipleChoiceApp.Bi.Exam.ExamServiceSoap.getAllAsync(MultipleChoiceApp.Bi.Exam.getAllRequest request) {
            return base.Channel.getAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Exam.getAllResponse> getAllAsync(int itemsPerPage, int currentPage) {
            MultipleChoiceApp.Bi.Exam.getAllRequest inValue = new MultipleChoiceApp.Bi.Exam.getAllRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Exam.getAllRequestBody();
            inValue.Body.itemsPerPage = itemsPerPage;
            inValue.Body.currentPage = currentPage;
            return ((MultipleChoiceApp.Bi.Exam.ExamServiceSoap)(this)).getAllAsync(inValue);
        }
        
        public int countAll() {
            return base.Channel.countAll();
        }
        
        public System.Threading.Tasks.Task<int> countAllAsync() {
            return base.Channel.countAllAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Exam.getDetailsByIdResponse MultipleChoiceApp.Bi.Exam.ExamServiceSoap.getDetailsById(MultipleChoiceApp.Bi.Exam.getDetailsByIdRequest request) {
            return base.Channel.getDetailsById(request);
        }
        
        public MultipleChoiceApp.Bi.Exam.Exam getDetailsById(int id) {
            MultipleChoiceApp.Bi.Exam.getDetailsByIdRequest inValue = new MultipleChoiceApp.Bi.Exam.getDetailsByIdRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Exam.getDetailsByIdRequestBody();
            inValue.Body.id = id;
            MultipleChoiceApp.Bi.Exam.getDetailsByIdResponse retVal = ((MultipleChoiceApp.Bi.Exam.ExamServiceSoap)(this)).getDetailsById(inValue);
            return retVal.Body.getDetailsByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Exam.getDetailsByIdResponse> MultipleChoiceApp.Bi.Exam.ExamServiceSoap.getDetailsByIdAsync(MultipleChoiceApp.Bi.Exam.getDetailsByIdRequest request) {
            return base.Channel.getDetailsByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Exam.getDetailsByIdResponse> getDetailsByIdAsync(int id) {
            MultipleChoiceApp.Bi.Exam.getDetailsByIdRequest inValue = new MultipleChoiceApp.Bi.Exam.getDetailsByIdRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Exam.getDetailsByIdRequestBody();
            inValue.Body.id = id;
            return ((MultipleChoiceApp.Bi.Exam.ExamServiceSoap)(this)).getDetailsByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Exam.addResponse MultipleChoiceApp.Bi.Exam.ExamServiceSoap.add(MultipleChoiceApp.Bi.Exam.addRequest request) {
            return base.Channel.add(request);
        }
        
        public bool add(MultipleChoiceApp.Bi.Exam.Exam item) {
            MultipleChoiceApp.Bi.Exam.addRequest inValue = new MultipleChoiceApp.Bi.Exam.addRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Exam.addRequestBody();
            inValue.Body.item = item;
            MultipleChoiceApp.Bi.Exam.addResponse retVal = ((MultipleChoiceApp.Bi.Exam.ExamServiceSoap)(this)).add(inValue);
            return retVal.Body.addResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Exam.addResponse> MultipleChoiceApp.Bi.Exam.ExamServiceSoap.addAsync(MultipleChoiceApp.Bi.Exam.addRequest request) {
            return base.Channel.addAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Exam.addResponse> addAsync(MultipleChoiceApp.Bi.Exam.Exam item) {
            MultipleChoiceApp.Bi.Exam.addRequest inValue = new MultipleChoiceApp.Bi.Exam.addRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Exam.addRequestBody();
            inValue.Body.item = item;
            return ((MultipleChoiceApp.Bi.Exam.ExamServiceSoap)(this)).addAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Exam.addManyResponse MultipleChoiceApp.Bi.Exam.ExamServiceSoap.addMany(MultipleChoiceApp.Bi.Exam.addManyRequest request) {
            return base.Channel.addMany(request);
        }
        
        public int addMany(System.Collections.Generic.List<MultipleChoiceApp.Bi.Exam.Exam> list) {
            MultipleChoiceApp.Bi.Exam.addManyRequest inValue = new MultipleChoiceApp.Bi.Exam.addManyRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Exam.addManyRequestBody();
            inValue.Body.list = list;
            MultipleChoiceApp.Bi.Exam.addManyResponse retVal = ((MultipleChoiceApp.Bi.Exam.ExamServiceSoap)(this)).addMany(inValue);
            return retVal.Body.addManyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Exam.addManyResponse> MultipleChoiceApp.Bi.Exam.ExamServiceSoap.addManyAsync(MultipleChoiceApp.Bi.Exam.addManyRequest request) {
            return base.Channel.addManyAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Exam.addManyResponse> addManyAsync(System.Collections.Generic.List<MultipleChoiceApp.Bi.Exam.Exam> list) {
            MultipleChoiceApp.Bi.Exam.addManyRequest inValue = new MultipleChoiceApp.Bi.Exam.addManyRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Exam.addManyRequestBody();
            inValue.Body.list = list;
            return ((MultipleChoiceApp.Bi.Exam.ExamServiceSoap)(this)).addManyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Exam.updateResponse MultipleChoiceApp.Bi.Exam.ExamServiceSoap.update(MultipleChoiceApp.Bi.Exam.updateRequest request) {
            return base.Channel.update(request);
        }
        
        public bool update(MultipleChoiceApp.Bi.Exam.Exam item) {
            MultipleChoiceApp.Bi.Exam.updateRequest inValue = new MultipleChoiceApp.Bi.Exam.updateRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Exam.updateRequestBody();
            inValue.Body.item = item;
            MultipleChoiceApp.Bi.Exam.updateResponse retVal = ((MultipleChoiceApp.Bi.Exam.ExamServiceSoap)(this)).update(inValue);
            return retVal.Body.updateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Exam.updateResponse> MultipleChoiceApp.Bi.Exam.ExamServiceSoap.updateAsync(MultipleChoiceApp.Bi.Exam.updateRequest request) {
            return base.Channel.updateAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Exam.updateResponse> updateAsync(MultipleChoiceApp.Bi.Exam.Exam item) {
            MultipleChoiceApp.Bi.Exam.updateRequest inValue = new MultipleChoiceApp.Bi.Exam.updateRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Exam.updateRequestBody();
            inValue.Body.item = item;
            return ((MultipleChoiceApp.Bi.Exam.ExamServiceSoap)(this)).updateAsync(inValue);
        }
        
        public bool delete(int id) {
            return base.Channel.delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> deleteAsync(int id) {
            return base.Channel.deleteAsync(id);
        }
    }
}
