//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultipleChoiceApp.Bi.StudentResponse {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StudentResponse", Namespace="http://peteranh.com/Services/StudentResponse")]
    [System.SerializableAttribute()]
    public partial class StudentResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int StudentResultIdField;
        
        private int QuestionIdField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MultipleChoiceApp.Bi.StudentResponse.Question QuestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MultipleChoiceApp.Bi.StudentResponse.ArrayOfInt AnswerOrderField;
        
        private int AnswerNOField;
        
        private int RandomAnswerNoField;
        
        private int NoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int StudentResultId {
            get {
                return this.StudentResultIdField;
            }
            set {
                if ((this.StudentResultIdField.Equals(value) != true)) {
                    this.StudentResultIdField = value;
                    this.RaisePropertyChanged("StudentResultId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int QuestionId {
            get {
                return this.QuestionIdField;
            }
            set {
                if ((this.QuestionIdField.Equals(value) != true)) {
                    this.QuestionIdField = value;
                    this.RaisePropertyChanged("QuestionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public MultipleChoiceApp.Bi.StudentResponse.Question Question {
            get {
                return this.QuestionField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionField, value) != true)) {
                    this.QuestionField = value;
                    this.RaisePropertyChanged("Question");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public MultipleChoiceApp.Bi.StudentResponse.ArrayOfInt AnswerOrder {
            get {
                return this.AnswerOrderField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswerOrderField, value) != true)) {
                    this.AnswerOrderField = value;
                    this.RaisePropertyChanged("AnswerOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int AnswerNO {
            get {
                return this.AnswerNOField;
            }
            set {
                if ((this.AnswerNOField.Equals(value) != true)) {
                    this.AnswerNOField = value;
                    this.RaisePropertyChanged("AnswerNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int RandomAnswerNo {
            get {
                return this.RandomAnswerNoField;
            }
            set {
                if ((this.RandomAnswerNoField.Equals(value) != true)) {
                    this.RandomAnswerNoField = value;
                    this.RaisePropertyChanged("RandomAnswerNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int No {
            get {
                return this.NoField;
            }
            set {
                if ((this.NoField.Equals(value) != true)) {
                    this.NoField = value;
                    this.RaisePropertyChanged("No");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Question", Namespace="http://peteranh.com/Services/StudentResponse")]
    [System.SerializableAttribute()]
    public partial class Question : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        private int SubjectIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LevelField;
        
        private int ChapterField;
        
        private int CorrectAnswerNoField;
        
        private System.DateTime CreatedAtField;
        
        private int CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LecturerField;
        
        private int QuestionInExamCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<MultipleChoiceApp.Bi.StudentResponse.Answer> AnswersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int SubjectId {
            get {
                return this.SubjectIdField;
            }
            set {
                if ((this.SubjectIdField.Equals(value) != true)) {
                    this.SubjectIdField = value;
                    this.RaisePropertyChanged("SubjectId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SubjectCode {
            get {
                return this.SubjectCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectCodeField, value) != true)) {
                    this.SubjectCodeField = value;
                    this.RaisePropertyChanged("SubjectCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Level {
            get {
                return this.LevelField;
            }
            set {
                if ((object.ReferenceEquals(this.LevelField, value) != true)) {
                    this.LevelField = value;
                    this.RaisePropertyChanged("Level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Chapter {
            get {
                return this.ChapterField;
            }
            set {
                if ((this.ChapterField.Equals(value) != true)) {
                    this.ChapterField = value;
                    this.RaisePropertyChanged("Chapter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int CorrectAnswerNo {
            get {
                return this.CorrectAnswerNoField;
            }
            set {
                if ((this.CorrectAnswerNoField.Equals(value) != true)) {
                    this.CorrectAnswerNoField = value;
                    this.RaisePropertyChanged("CorrectAnswerNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime CreatedAt {
            get {
                return this.CreatedAtField;
            }
            set {
                if ((this.CreatedAtField.Equals(value) != true)) {
                    this.CreatedAtField = value;
                    this.RaisePropertyChanged("CreatedAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((this.CreatedByField.Equals(value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Lecturer {
            get {
                return this.LecturerField;
            }
            set {
                if ((object.ReferenceEquals(this.LecturerField, value) != true)) {
                    this.LecturerField = value;
                    this.RaisePropertyChanged("Lecturer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int QuestionInExamCount {
            get {
                return this.QuestionInExamCountField;
            }
            set {
                if ((this.QuestionInExamCountField.Equals(value) != true)) {
                    this.QuestionInExamCountField = value;
                    this.RaisePropertyChanged("QuestionInExamCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.StudentResponse.Answer> Answers {
            get {
                return this.AnswersField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswersField, value) != true)) {
                    this.AnswersField = value;
                    this.RaisePropertyChanged("Answers");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://peteranh.com/Services/StudentResponse", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Answer", Namespace="http://peteranh.com/Services/StudentResponse")]
    [System.SerializableAttribute()]
    public partial class Answer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int QuestionIdField;
        
        private int NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        private int AnswerCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int QuestionId {
            get {
                return this.QuestionIdField;
            }
            set {
                if ((this.QuestionIdField.Equals(value) != true)) {
                    this.QuestionIdField = value;
                    this.RaisePropertyChanged("QuestionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int No {
            get {
                return this.NoField;
            }
            set {
                if ((this.NoField.Equals(value) != true)) {
                    this.NoField = value;
                    this.RaisePropertyChanged("No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int AnswerCount {
            get {
                return this.AnswerCountField;
            }
            set {
                if ((this.AnswerCountField.Equals(value) != true)) {
                    this.AnswerCountField = value;
                    this.RaisePropertyChanged("AnswerCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://peteranh.com/Services/StudentResponse", ConfigurationName="Bi.StudentResponse.StudentResponseServiceSoap")]
    public interface StudentResponseServiceSoap {
        
        // CODEGEN: Generating message contract since element name getAllByExamAndStudentIdResult from namespace http://peteranh.com/Services/StudentResponse is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/StudentResponse/getAllByExamAndStudentId", ReplyAction="*")]
        MultipleChoiceApp.Bi.StudentResponse.getAllByExamAndStudentIdResponse getAllByExamAndStudentId(MultipleChoiceApp.Bi.StudentResponse.getAllByExamAndStudentIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/StudentResponse/getAllByExamAndStudentId", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.StudentResponse.getAllByExamAndStudentIdResponse> getAllByExamAndStudentIdAsync(MultipleChoiceApp.Bi.StudentResponse.getAllByExamAndStudentIdRequest request);
        
        // CODEGEN: Generating message contract since element name getAllForSelectDataResult from namespace http://peteranh.com/Services/StudentResponse is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/StudentResponse/getAllForSelectData", ReplyAction="*")]
        MultipleChoiceApp.Bi.StudentResponse.getAllForSelectDataResponse getAllForSelectData(MultipleChoiceApp.Bi.StudentResponse.getAllForSelectDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/StudentResponse/getAllForSelectData", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.StudentResponse.getAllForSelectDataResponse> getAllForSelectDataAsync(MultipleChoiceApp.Bi.StudentResponse.getAllForSelectDataRequest request);
        
        // CODEGEN: Generating message contract since element name getAllResult from namespace http://peteranh.com/Services/StudentResponse is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/StudentResponse/getAll", ReplyAction="*")]
        MultipleChoiceApp.Bi.StudentResponse.getAllResponse getAll(MultipleChoiceApp.Bi.StudentResponse.getAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/StudentResponse/getAll", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.StudentResponse.getAllResponse> getAllAsync(MultipleChoiceApp.Bi.StudentResponse.getAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/StudentResponse/countAll", ReplyAction="*")]
        int countAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/StudentResponse/countAll", ReplyAction="*")]
        System.Threading.Tasks.Task<int> countAllAsync();
        
        // CODEGEN: Generating message contract since element name getDetailsByIdResult from namespace http://peteranh.com/Services/StudentResponse is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/StudentResponse/getDetailsById", ReplyAction="*")]
        MultipleChoiceApp.Bi.StudentResponse.getDetailsByIdResponse getDetailsById(MultipleChoiceApp.Bi.StudentResponse.getDetailsByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/StudentResponse/getDetailsById", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.StudentResponse.getDetailsByIdResponse> getDetailsByIdAsync(MultipleChoiceApp.Bi.StudentResponse.getDetailsByIdRequest request);
        
        // CODEGEN: Generating message contract since element name item from namespace http://peteranh.com/Services/StudentResponse is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/StudentResponse/add", ReplyAction="*")]
        MultipleChoiceApp.Bi.StudentResponse.addResponse add(MultipleChoiceApp.Bi.StudentResponse.addRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/StudentResponse/add", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.StudentResponse.addResponse> addAsync(MultipleChoiceApp.Bi.StudentResponse.addRequest request);
        
        // CODEGEN: Generating message contract since element name list from namespace http://peteranh.com/Services/StudentResponse is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/StudentResponse/addMany", ReplyAction="*")]
        MultipleChoiceApp.Bi.StudentResponse.addManyResponse addMany(MultipleChoiceApp.Bi.StudentResponse.addManyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/StudentResponse/addMany", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.StudentResponse.addManyResponse> addManyAsync(MultipleChoiceApp.Bi.StudentResponse.addManyRequest request);
        
        // CODEGEN: Generating message contract since element name item from namespace http://peteranh.com/Services/StudentResponse is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/StudentResponse/update", ReplyAction="*")]
        MultipleChoiceApp.Bi.StudentResponse.updateResponse update(MultipleChoiceApp.Bi.StudentResponse.updateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/StudentResponse/update", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.StudentResponse.updateResponse> updateAsync(MultipleChoiceApp.Bi.StudentResponse.updateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/StudentResponse/delete", ReplyAction="*")]
        bool delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/StudentResponse/delete", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> deleteAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllByExamAndStudentIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllByExamAndStudentId", Namespace="http://peteranh.com/Services/StudentResponse", Order=0)]
        public MultipleChoiceApp.Bi.StudentResponse.getAllByExamAndStudentIdRequestBody Body;
        
        public getAllByExamAndStudentIdRequest() {
        }
        
        public getAllByExamAndStudentIdRequest(MultipleChoiceApp.Bi.StudentResponse.getAllByExamAndStudentIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/StudentResponse")]
    public partial class getAllByExamAndStudentIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int examId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int studentId;
        
        public getAllByExamAndStudentIdRequestBody() {
        }
        
        public getAllByExamAndStudentIdRequestBody(int examId, int studentId) {
            this.examId = examId;
            this.studentId = studentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllByExamAndStudentIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllByExamAndStudentIdResponse", Namespace="http://peteranh.com/Services/StudentResponse", Order=0)]
        public MultipleChoiceApp.Bi.StudentResponse.getAllByExamAndStudentIdResponseBody Body;
        
        public getAllByExamAndStudentIdResponse() {
        }
        
        public getAllByExamAndStudentIdResponse(MultipleChoiceApp.Bi.StudentResponse.getAllByExamAndStudentIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/StudentResponse")]
    public partial class getAllByExamAndStudentIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.StudentResponse.StudentResponse> getAllByExamAndStudentIdResult;
        
        public getAllByExamAndStudentIdResponseBody() {
        }
        
        public getAllByExamAndStudentIdResponseBody(System.Collections.Generic.List<MultipleChoiceApp.Bi.StudentResponse.StudentResponse> getAllByExamAndStudentIdResult) {
            this.getAllByExamAndStudentIdResult = getAllByExamAndStudentIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllForSelectDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllForSelectData", Namespace="http://peteranh.com/Services/StudentResponse", Order=0)]
        public MultipleChoiceApp.Bi.StudentResponse.getAllForSelectDataRequestBody Body;
        
        public getAllForSelectDataRequest() {
        }
        
        public getAllForSelectDataRequest(MultipleChoiceApp.Bi.StudentResponse.getAllForSelectDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getAllForSelectDataRequestBody {
        
        public getAllForSelectDataRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllForSelectDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllForSelectDataResponse", Namespace="http://peteranh.com/Services/StudentResponse", Order=0)]
        public MultipleChoiceApp.Bi.StudentResponse.getAllForSelectDataResponseBody Body;
        
        public getAllForSelectDataResponse() {
        }
        
        public getAllForSelectDataResponse(MultipleChoiceApp.Bi.StudentResponse.getAllForSelectDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/StudentResponse")]
    public partial class getAllForSelectDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.StudentResponse.StudentResponse> getAllForSelectDataResult;
        
        public getAllForSelectDataResponseBody() {
        }
        
        public getAllForSelectDataResponseBody(System.Collections.Generic.List<MultipleChoiceApp.Bi.StudentResponse.StudentResponse> getAllForSelectDataResult) {
            this.getAllForSelectDataResult = getAllForSelectDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAll", Namespace="http://peteranh.com/Services/StudentResponse", Order=0)]
        public MultipleChoiceApp.Bi.StudentResponse.getAllRequestBody Body;
        
        public getAllRequest() {
        }
        
        public getAllRequest(MultipleChoiceApp.Bi.StudentResponse.getAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/StudentResponse")]
    public partial class getAllRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int itemsPerPage;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int currentPage;
        
        public getAllRequestBody() {
        }
        
        public getAllRequestBody(int itemsPerPage, int currentPage) {
            this.itemsPerPage = itemsPerPage;
            this.currentPage = currentPage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllResponse", Namespace="http://peteranh.com/Services/StudentResponse", Order=0)]
        public MultipleChoiceApp.Bi.StudentResponse.getAllResponseBody Body;
        
        public getAllResponse() {
        }
        
        public getAllResponse(MultipleChoiceApp.Bi.StudentResponse.getAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/StudentResponse")]
    public partial class getAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.StudentResponse.StudentResponse> getAllResult;
        
        public getAllResponseBody() {
        }
        
        public getAllResponseBody(System.Collections.Generic.List<MultipleChoiceApp.Bi.StudentResponse.StudentResponse> getAllResult) {
            this.getAllResult = getAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDetailsByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDetailsById", Namespace="http://peteranh.com/Services/StudentResponse", Order=0)]
        public MultipleChoiceApp.Bi.StudentResponse.getDetailsByIdRequestBody Body;
        
        public getDetailsByIdRequest() {
        }
        
        public getDetailsByIdRequest(MultipleChoiceApp.Bi.StudentResponse.getDetailsByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/StudentResponse")]
    public partial class getDetailsByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public getDetailsByIdRequestBody() {
        }
        
        public getDetailsByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDetailsByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDetailsByIdResponse", Namespace="http://peteranh.com/Services/StudentResponse", Order=0)]
        public MultipleChoiceApp.Bi.StudentResponse.getDetailsByIdResponseBody Body;
        
        public getDetailsByIdResponse() {
        }
        
        public getDetailsByIdResponse(MultipleChoiceApp.Bi.StudentResponse.getDetailsByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/StudentResponse")]
    public partial class getDetailsByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MultipleChoiceApp.Bi.StudentResponse.StudentResponse getDetailsByIdResult;
        
        public getDetailsByIdResponseBody() {
        }
        
        public getDetailsByIdResponseBody(MultipleChoiceApp.Bi.StudentResponse.StudentResponse getDetailsByIdResult) {
            this.getDetailsByIdResult = getDetailsByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="add", Namespace="http://peteranh.com/Services/StudentResponse", Order=0)]
        public MultipleChoiceApp.Bi.StudentResponse.addRequestBody Body;
        
        public addRequest() {
        }
        
        public addRequest(MultipleChoiceApp.Bi.StudentResponse.addRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/StudentResponse")]
    public partial class addRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MultipleChoiceApp.Bi.StudentResponse.StudentResponse item;
        
        public addRequestBody() {
        }
        
        public addRequestBody(MultipleChoiceApp.Bi.StudentResponse.StudentResponse item) {
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addResponse", Namespace="http://peteranh.com/Services/StudentResponse", Order=0)]
        public MultipleChoiceApp.Bi.StudentResponse.addResponseBody Body;
        
        public addResponse() {
        }
        
        public addResponse(MultipleChoiceApp.Bi.StudentResponse.addResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/StudentResponse")]
    public partial class addResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool addResult;
        
        public addResponseBody() {
        }
        
        public addResponseBody(bool addResult) {
            this.addResult = addResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addManyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addMany", Namespace="http://peteranh.com/Services/StudentResponse", Order=0)]
        public MultipleChoiceApp.Bi.StudentResponse.addManyRequestBody Body;
        
        public addManyRequest() {
        }
        
        public addManyRequest(MultipleChoiceApp.Bi.StudentResponse.addManyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/StudentResponse")]
    public partial class addManyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.StudentResponse.StudentResponse> list;
        
        public addManyRequestBody() {
        }
        
        public addManyRequestBody(System.Collections.Generic.List<MultipleChoiceApp.Bi.StudentResponse.StudentResponse> list) {
            this.list = list;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addManyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addManyResponse", Namespace="http://peteranh.com/Services/StudentResponse", Order=0)]
        public MultipleChoiceApp.Bi.StudentResponse.addManyResponseBody Body;
        
        public addManyResponse() {
        }
        
        public addManyResponse(MultipleChoiceApp.Bi.StudentResponse.addManyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/StudentResponse")]
    public partial class addManyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int addManyResult;
        
        public addManyResponseBody() {
        }
        
        public addManyResponseBody(int addManyResult) {
            this.addManyResult = addManyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="update", Namespace="http://peteranh.com/Services/StudentResponse", Order=0)]
        public MultipleChoiceApp.Bi.StudentResponse.updateRequestBody Body;
        
        public updateRequest() {
        }
        
        public updateRequest(MultipleChoiceApp.Bi.StudentResponse.updateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/StudentResponse")]
    public partial class updateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MultipleChoiceApp.Bi.StudentResponse.StudentResponse item;
        
        public updateRequestBody() {
        }
        
        public updateRequestBody(MultipleChoiceApp.Bi.StudentResponse.StudentResponse item) {
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateResponse", Namespace="http://peteranh.com/Services/StudentResponse", Order=0)]
        public MultipleChoiceApp.Bi.StudentResponse.updateResponseBody Body;
        
        public updateResponse() {
        }
        
        public updateResponse(MultipleChoiceApp.Bi.StudentResponse.updateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/StudentResponse")]
    public partial class updateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool updateResult;
        
        public updateResponseBody() {
        }
        
        public updateResponseBody(bool updateResult) {
            this.updateResult = updateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StudentResponseServiceSoapChannel : MultipleChoiceApp.Bi.StudentResponse.StudentResponseServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentResponseServiceSoapClient : System.ServiceModel.ClientBase<MultipleChoiceApp.Bi.StudentResponse.StudentResponseServiceSoap>, MultipleChoiceApp.Bi.StudentResponse.StudentResponseServiceSoap {
        
        public StudentResponseServiceSoapClient() {
        }
        
        public StudentResponseServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentResponseServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentResponseServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentResponseServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.StudentResponse.getAllByExamAndStudentIdResponse MultipleChoiceApp.Bi.StudentResponse.StudentResponseServiceSoap.getAllByExamAndStudentId(MultipleChoiceApp.Bi.StudentResponse.getAllByExamAndStudentIdRequest request) {
            return base.Channel.getAllByExamAndStudentId(request);
        }
        
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.StudentResponse.StudentResponse> getAllByExamAndStudentId(int examId, int studentId) {
            MultipleChoiceApp.Bi.StudentResponse.getAllByExamAndStudentIdRequest inValue = new MultipleChoiceApp.Bi.StudentResponse.getAllByExamAndStudentIdRequest();
            inValue.Body = new MultipleChoiceApp.Bi.StudentResponse.getAllByExamAndStudentIdRequestBody();
            inValue.Body.examId = examId;
            inValue.Body.studentId = studentId;
            MultipleChoiceApp.Bi.StudentResponse.getAllByExamAndStudentIdResponse retVal = ((MultipleChoiceApp.Bi.StudentResponse.StudentResponseServiceSoap)(this)).getAllByExamAndStudentId(inValue);
            return retVal.Body.getAllByExamAndStudentIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.StudentResponse.getAllByExamAndStudentIdResponse> MultipleChoiceApp.Bi.StudentResponse.StudentResponseServiceSoap.getAllByExamAndStudentIdAsync(MultipleChoiceApp.Bi.StudentResponse.getAllByExamAndStudentIdRequest request) {
            return base.Channel.getAllByExamAndStudentIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.StudentResponse.getAllByExamAndStudentIdResponse> getAllByExamAndStudentIdAsync(int examId, int studentId) {
            MultipleChoiceApp.Bi.StudentResponse.getAllByExamAndStudentIdRequest inValue = new MultipleChoiceApp.Bi.StudentResponse.getAllByExamAndStudentIdRequest();
            inValue.Body = new MultipleChoiceApp.Bi.StudentResponse.getAllByExamAndStudentIdRequestBody();
            inValue.Body.examId = examId;
            inValue.Body.studentId = studentId;
            return ((MultipleChoiceApp.Bi.StudentResponse.StudentResponseServiceSoap)(this)).getAllByExamAndStudentIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.StudentResponse.getAllForSelectDataResponse MultipleChoiceApp.Bi.StudentResponse.StudentResponseServiceSoap.getAllForSelectData(MultipleChoiceApp.Bi.StudentResponse.getAllForSelectDataRequest request) {
            return base.Channel.getAllForSelectData(request);
        }
        
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.StudentResponse.StudentResponse> getAllForSelectData() {
            MultipleChoiceApp.Bi.StudentResponse.getAllForSelectDataRequest inValue = new MultipleChoiceApp.Bi.StudentResponse.getAllForSelectDataRequest();
            inValue.Body = new MultipleChoiceApp.Bi.StudentResponse.getAllForSelectDataRequestBody();
            MultipleChoiceApp.Bi.StudentResponse.getAllForSelectDataResponse retVal = ((MultipleChoiceApp.Bi.StudentResponse.StudentResponseServiceSoap)(this)).getAllForSelectData(inValue);
            return retVal.Body.getAllForSelectDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.StudentResponse.getAllForSelectDataResponse> MultipleChoiceApp.Bi.StudentResponse.StudentResponseServiceSoap.getAllForSelectDataAsync(MultipleChoiceApp.Bi.StudentResponse.getAllForSelectDataRequest request) {
            return base.Channel.getAllForSelectDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.StudentResponse.getAllForSelectDataResponse> getAllForSelectDataAsync() {
            MultipleChoiceApp.Bi.StudentResponse.getAllForSelectDataRequest inValue = new MultipleChoiceApp.Bi.StudentResponse.getAllForSelectDataRequest();
            inValue.Body = new MultipleChoiceApp.Bi.StudentResponse.getAllForSelectDataRequestBody();
            return ((MultipleChoiceApp.Bi.StudentResponse.StudentResponseServiceSoap)(this)).getAllForSelectDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.StudentResponse.getAllResponse MultipleChoiceApp.Bi.StudentResponse.StudentResponseServiceSoap.getAll(MultipleChoiceApp.Bi.StudentResponse.getAllRequest request) {
            return base.Channel.getAll(request);
        }
        
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.StudentResponse.StudentResponse> getAll(int itemsPerPage, int currentPage) {
            MultipleChoiceApp.Bi.StudentResponse.getAllRequest inValue = new MultipleChoiceApp.Bi.StudentResponse.getAllRequest();
            inValue.Body = new MultipleChoiceApp.Bi.StudentResponse.getAllRequestBody();
            inValue.Body.itemsPerPage = itemsPerPage;
            inValue.Body.currentPage = currentPage;
            MultipleChoiceApp.Bi.StudentResponse.getAllResponse retVal = ((MultipleChoiceApp.Bi.StudentResponse.StudentResponseServiceSoap)(this)).getAll(inValue);
            return retVal.Body.getAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.StudentResponse.getAllResponse> MultipleChoiceApp.Bi.StudentResponse.StudentResponseServiceSoap.getAllAsync(MultipleChoiceApp.Bi.StudentResponse.getAllRequest request) {
            return base.Channel.getAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.StudentResponse.getAllResponse> getAllAsync(int itemsPerPage, int currentPage) {
            MultipleChoiceApp.Bi.StudentResponse.getAllRequest inValue = new MultipleChoiceApp.Bi.StudentResponse.getAllRequest();
            inValue.Body = new MultipleChoiceApp.Bi.StudentResponse.getAllRequestBody();
            inValue.Body.itemsPerPage = itemsPerPage;
            inValue.Body.currentPage = currentPage;
            return ((MultipleChoiceApp.Bi.StudentResponse.StudentResponseServiceSoap)(this)).getAllAsync(inValue);
        }
        
        public int countAll() {
            return base.Channel.countAll();
        }
        
        public System.Threading.Tasks.Task<int> countAllAsync() {
            return base.Channel.countAllAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.StudentResponse.getDetailsByIdResponse MultipleChoiceApp.Bi.StudentResponse.StudentResponseServiceSoap.getDetailsById(MultipleChoiceApp.Bi.StudentResponse.getDetailsByIdRequest request) {
            return base.Channel.getDetailsById(request);
        }
        
        public MultipleChoiceApp.Bi.StudentResponse.StudentResponse getDetailsById(int id) {
            MultipleChoiceApp.Bi.StudentResponse.getDetailsByIdRequest inValue = new MultipleChoiceApp.Bi.StudentResponse.getDetailsByIdRequest();
            inValue.Body = new MultipleChoiceApp.Bi.StudentResponse.getDetailsByIdRequestBody();
            inValue.Body.id = id;
            MultipleChoiceApp.Bi.StudentResponse.getDetailsByIdResponse retVal = ((MultipleChoiceApp.Bi.StudentResponse.StudentResponseServiceSoap)(this)).getDetailsById(inValue);
            return retVal.Body.getDetailsByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.StudentResponse.getDetailsByIdResponse> MultipleChoiceApp.Bi.StudentResponse.StudentResponseServiceSoap.getDetailsByIdAsync(MultipleChoiceApp.Bi.StudentResponse.getDetailsByIdRequest request) {
            return base.Channel.getDetailsByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.StudentResponse.getDetailsByIdResponse> getDetailsByIdAsync(int id) {
            MultipleChoiceApp.Bi.StudentResponse.getDetailsByIdRequest inValue = new MultipleChoiceApp.Bi.StudentResponse.getDetailsByIdRequest();
            inValue.Body = new MultipleChoiceApp.Bi.StudentResponse.getDetailsByIdRequestBody();
            inValue.Body.id = id;
            return ((MultipleChoiceApp.Bi.StudentResponse.StudentResponseServiceSoap)(this)).getDetailsByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.StudentResponse.addResponse MultipleChoiceApp.Bi.StudentResponse.StudentResponseServiceSoap.add(MultipleChoiceApp.Bi.StudentResponse.addRequest request) {
            return base.Channel.add(request);
        }
        
        public bool add(MultipleChoiceApp.Bi.StudentResponse.StudentResponse item) {
            MultipleChoiceApp.Bi.StudentResponse.addRequest inValue = new MultipleChoiceApp.Bi.StudentResponse.addRequest();
            inValue.Body = new MultipleChoiceApp.Bi.StudentResponse.addRequestBody();
            inValue.Body.item = item;
            MultipleChoiceApp.Bi.StudentResponse.addResponse retVal = ((MultipleChoiceApp.Bi.StudentResponse.StudentResponseServiceSoap)(this)).add(inValue);
            return retVal.Body.addResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.StudentResponse.addResponse> MultipleChoiceApp.Bi.StudentResponse.StudentResponseServiceSoap.addAsync(MultipleChoiceApp.Bi.StudentResponse.addRequest request) {
            return base.Channel.addAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.StudentResponse.addResponse> addAsync(MultipleChoiceApp.Bi.StudentResponse.StudentResponse item) {
            MultipleChoiceApp.Bi.StudentResponse.addRequest inValue = new MultipleChoiceApp.Bi.StudentResponse.addRequest();
            inValue.Body = new MultipleChoiceApp.Bi.StudentResponse.addRequestBody();
            inValue.Body.item = item;
            return ((MultipleChoiceApp.Bi.StudentResponse.StudentResponseServiceSoap)(this)).addAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.StudentResponse.addManyResponse MultipleChoiceApp.Bi.StudentResponse.StudentResponseServiceSoap.addMany(MultipleChoiceApp.Bi.StudentResponse.addManyRequest request) {
            return base.Channel.addMany(request);
        }
        
        public int addMany(System.Collections.Generic.List<MultipleChoiceApp.Bi.StudentResponse.StudentResponse> list) {
            MultipleChoiceApp.Bi.StudentResponse.addManyRequest inValue = new MultipleChoiceApp.Bi.StudentResponse.addManyRequest();
            inValue.Body = new MultipleChoiceApp.Bi.StudentResponse.addManyRequestBody();
            inValue.Body.list = list;
            MultipleChoiceApp.Bi.StudentResponse.addManyResponse retVal = ((MultipleChoiceApp.Bi.StudentResponse.StudentResponseServiceSoap)(this)).addMany(inValue);
            return retVal.Body.addManyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.StudentResponse.addManyResponse> MultipleChoiceApp.Bi.StudentResponse.StudentResponseServiceSoap.addManyAsync(MultipleChoiceApp.Bi.StudentResponse.addManyRequest request) {
            return base.Channel.addManyAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.StudentResponse.addManyResponse> addManyAsync(System.Collections.Generic.List<MultipleChoiceApp.Bi.StudentResponse.StudentResponse> list) {
            MultipleChoiceApp.Bi.StudentResponse.addManyRequest inValue = new MultipleChoiceApp.Bi.StudentResponse.addManyRequest();
            inValue.Body = new MultipleChoiceApp.Bi.StudentResponse.addManyRequestBody();
            inValue.Body.list = list;
            return ((MultipleChoiceApp.Bi.StudentResponse.StudentResponseServiceSoap)(this)).addManyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.StudentResponse.updateResponse MultipleChoiceApp.Bi.StudentResponse.StudentResponseServiceSoap.update(MultipleChoiceApp.Bi.StudentResponse.updateRequest request) {
            return base.Channel.update(request);
        }
        
        public bool update(MultipleChoiceApp.Bi.StudentResponse.StudentResponse item) {
            MultipleChoiceApp.Bi.StudentResponse.updateRequest inValue = new MultipleChoiceApp.Bi.StudentResponse.updateRequest();
            inValue.Body = new MultipleChoiceApp.Bi.StudentResponse.updateRequestBody();
            inValue.Body.item = item;
            MultipleChoiceApp.Bi.StudentResponse.updateResponse retVal = ((MultipleChoiceApp.Bi.StudentResponse.StudentResponseServiceSoap)(this)).update(inValue);
            return retVal.Body.updateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.StudentResponse.updateResponse> MultipleChoiceApp.Bi.StudentResponse.StudentResponseServiceSoap.updateAsync(MultipleChoiceApp.Bi.StudentResponse.updateRequest request) {
            return base.Channel.updateAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.StudentResponse.updateResponse> updateAsync(MultipleChoiceApp.Bi.StudentResponse.StudentResponse item) {
            MultipleChoiceApp.Bi.StudentResponse.updateRequest inValue = new MultipleChoiceApp.Bi.StudentResponse.updateRequest();
            inValue.Body = new MultipleChoiceApp.Bi.StudentResponse.updateRequestBody();
            inValue.Body.item = item;
            return ((MultipleChoiceApp.Bi.StudentResponse.StudentResponseServiceSoap)(this)).updateAsync(inValue);
        }
        
        public bool delete(int id) {
            return base.Channel.delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> deleteAsync(int id) {
            return base.Channel.deleteAsync(id);
        }
    }
}
