//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultipleChoiceApp.Bi.Student {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://peteranh.com/Services/Student", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://peteranh.com/Services/Student")]
    [System.SerializableAttribute()]
    public partial class Student : MultipleChoiceApp.Bi.Student.User {
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        private System.DateTime DOBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MajorField;
        
        private int CreatedByField;
        
        private int ExamStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime DOB {
            get {
                return this.DOBField;
            }
            set {
                if ((this.DOBField.Equals(value) != true)) {
                    this.DOBField = value;
                    this.RaisePropertyChanged("DOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Major {
            get {
                return this.MajorField;
            }
            set {
                if ((object.ReferenceEquals(this.MajorField, value) != true)) {
                    this.MajorField = value;
                    this.RaisePropertyChanged("Major");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((this.CreatedByField.Equals(value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int ExamStatus {
            get {
                return this.ExamStatusField;
            }
            set {
                if ((this.ExamStatusField.Equals(value) != true)) {
                    this.ExamStatusField = value;
                    this.RaisePropertyChanged("ExamStatus");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://peteranh.com/Services/Student")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MultipleChoiceApp.Bi.Student.Student))]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://peteranh.com/Services/Student", ConfigurationName="Bi.Student.StudentServiceSoap")]
    public interface StudentServiceSoap {
        
        // CODEGEN: Generating message contract since element name studentIds from namespace http://peteranh.com/Services/Student is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Student/setStudentsForExam", ReplyAction="*")]
        MultipleChoiceApp.Bi.Student.setStudentsForExamResponse setStudentsForExam(MultipleChoiceApp.Bi.Student.setStudentsForExamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Student/setStudentsForExam", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.setStudentsForExamResponse> setStudentsForExamAsync(MultipleChoiceApp.Bi.Student.setStudentsForExamRequest request);
        
        // CODEGEN: Generating message contract since element name getStudentsNotInExamResult from namespace http://peteranh.com/Services/Student is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Student/getStudentsNotInExam", ReplyAction="*")]
        MultipleChoiceApp.Bi.Student.getStudentsNotInExamResponse getStudentsNotInExam(MultipleChoiceApp.Bi.Student.getStudentsNotInExamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Student/getStudentsNotInExam", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.getStudentsNotInExamResponse> getStudentsNotInExamAsync(MultipleChoiceApp.Bi.Student.getStudentsNotInExamRequest request);
        
        // CODEGEN: Generating message contract since element name getStudentInExamResult from namespace http://peteranh.com/Services/Student is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Student/getStudentInExam", ReplyAction="*")]
        MultipleChoiceApp.Bi.Student.getStudentInExamResponse getStudentInExam(MultipleChoiceApp.Bi.Student.getStudentInExamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Student/getStudentInExam", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.getStudentInExamResponse> getStudentInExamAsync(MultipleChoiceApp.Bi.Student.getStudentInExamRequest request);
        
        // CODEGEN: Generating message contract since element name studentIds from namespace http://peteranh.com/Services/Student is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Student/addStudentsToExam", ReplyAction="*")]
        MultipleChoiceApp.Bi.Student.addStudentsToExamResponse addStudentsToExam(MultipleChoiceApp.Bi.Student.addStudentsToExamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Student/addStudentsToExam", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.addStudentsToExamResponse> addStudentsToExamAsync(MultipleChoiceApp.Bi.Student.addStudentsToExamRequest request);
        
        // CODEGEN: Generating message contract since element name studentIds from namespace http://peteranh.com/Services/Student is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Student/removeStudentsFromExam", ReplyAction="*")]
        MultipleChoiceApp.Bi.Student.removeStudentsFromExamResponse removeStudentsFromExam(MultipleChoiceApp.Bi.Student.removeStudentsFromExamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Student/removeStudentsFromExam", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.removeStudentsFromExamResponse> removeStudentsFromExamAsync(MultipleChoiceApp.Bi.Student.removeStudentsFromExamRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://peteranh.com/Services/Student is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Student/getByCodeAndPassword", ReplyAction="*")]
        MultipleChoiceApp.Bi.Student.getByCodeAndPasswordResponse getByCodeAndPassword(MultipleChoiceApp.Bi.Student.getByCodeAndPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Student/getByCodeAndPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.getByCodeAndPasswordResponse> getByCodeAndPasswordAsync(MultipleChoiceApp.Bi.Student.getByCodeAndPasswordRequest request);
        
        // CODEGEN: Generating message contract since element name keyword from namespace http://peteranh.com/Services/Student is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Student/searchByKeyword", ReplyAction="*")]
        MultipleChoiceApp.Bi.Student.searchByKeywordResponse searchByKeyword(MultipleChoiceApp.Bi.Student.searchByKeywordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Student/searchByKeyword", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.searchByKeywordResponse> searchByKeywordAsync(MultipleChoiceApp.Bi.Student.searchByKeywordRequest request);
        
        // CODEGEN: Generating message contract since element name code from namespace http://peteranh.com/Services/Student is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Student/getByCode", ReplyAction="*")]
        MultipleChoiceApp.Bi.Student.getByCodeResponse getByCode(MultipleChoiceApp.Bi.Student.getByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Student/getByCode", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.getByCodeResponse> getByCodeAsync(MultipleChoiceApp.Bi.Student.getByCodeRequest request);
        
        // CODEGEN: Generating message contract since element name getAllForSelectDataResult from namespace http://peteranh.com/Services/Student is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Student/getAllForSelectData", ReplyAction="*")]
        MultipleChoiceApp.Bi.Student.getAllForSelectDataResponse getAllForSelectData(MultipleChoiceApp.Bi.Student.getAllForSelectDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Student/getAllForSelectData", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.getAllForSelectDataResponse> getAllForSelectDataAsync(MultipleChoiceApp.Bi.Student.getAllForSelectDataRequest request);
        
        // CODEGEN: Generating message contract since element name getAllResult from namespace http://peteranh.com/Services/Student is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Student/getAll", ReplyAction="*")]
        MultipleChoiceApp.Bi.Student.getAllResponse getAll(MultipleChoiceApp.Bi.Student.getAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Student/getAll", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.getAllResponse> getAllAsync(MultipleChoiceApp.Bi.Student.getAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Student/countAll", ReplyAction="*")]
        int countAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Student/countAll", ReplyAction="*")]
        System.Threading.Tasks.Task<int> countAllAsync();
        
        // CODEGEN: Generating message contract since element name getDetailsByIdResult from namespace http://peteranh.com/Services/Student is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Student/getDetailsById", ReplyAction="*")]
        MultipleChoiceApp.Bi.Student.getDetailsByIdResponse getDetailsById(MultipleChoiceApp.Bi.Student.getDetailsByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Student/getDetailsById", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.getDetailsByIdResponse> getDetailsByIdAsync(MultipleChoiceApp.Bi.Student.getDetailsByIdRequest request);
        
        // CODEGEN: Generating message contract since element name item from namespace http://peteranh.com/Services/Student is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Student/add", ReplyAction="*")]
        MultipleChoiceApp.Bi.Student.addResponse add(MultipleChoiceApp.Bi.Student.addRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Student/add", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.addResponse> addAsync(MultipleChoiceApp.Bi.Student.addRequest request);
        
        // CODEGEN: Generating message contract since element name list from namespace http://peteranh.com/Services/Student is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Student/addMany", ReplyAction="*")]
        MultipleChoiceApp.Bi.Student.addManyResponse addMany(MultipleChoiceApp.Bi.Student.addManyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Student/addMany", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.addManyResponse> addManyAsync(MultipleChoiceApp.Bi.Student.addManyRequest request);
        
        // CODEGEN: Generating message contract since element name item from namespace http://peteranh.com/Services/Student is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Student/update", ReplyAction="*")]
        MultipleChoiceApp.Bi.Student.updateResponse update(MultipleChoiceApp.Bi.Student.updateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Student/update", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.updateResponse> updateAsync(MultipleChoiceApp.Bi.Student.updateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Student/delete", ReplyAction="*")]
        bool delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Student/delete", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> deleteAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setStudentsForExamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setStudentsForExam", Namespace="http://peteranh.com/Services/Student", Order=0)]
        public MultipleChoiceApp.Bi.Student.setStudentsForExamRequestBody Body;
        
        public setStudentsForExamRequest() {
        }
        
        public setStudentsForExamRequest(MultipleChoiceApp.Bi.Student.setStudentsForExamRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Student")]
    public partial class setStudentsForExamRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MultipleChoiceApp.Bi.Student.ArrayOfInt studentIds;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int examId;
        
        public setStudentsForExamRequestBody() {
        }
        
        public setStudentsForExamRequestBody(MultipleChoiceApp.Bi.Student.ArrayOfInt studentIds, int examId) {
            this.studentIds = studentIds;
            this.examId = examId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setStudentsForExamResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setStudentsForExamResponse", Namespace="http://peteranh.com/Services/Student", Order=0)]
        public MultipleChoiceApp.Bi.Student.setStudentsForExamResponseBody Body;
        
        public setStudentsForExamResponse() {
        }
        
        public setStudentsForExamResponse(MultipleChoiceApp.Bi.Student.setStudentsForExamResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Student")]
    public partial class setStudentsForExamResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int setStudentsForExamResult;
        
        public setStudentsForExamResponseBody() {
        }
        
        public setStudentsForExamResponseBody(int setStudentsForExamResult) {
            this.setStudentsForExamResult = setStudentsForExamResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStudentsNotInExamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getStudentsNotInExam", Namespace="http://peteranh.com/Services/Student", Order=0)]
        public MultipleChoiceApp.Bi.Student.getStudentsNotInExamRequestBody Body;
        
        public getStudentsNotInExamRequest() {
        }
        
        public getStudentsNotInExamRequest(MultipleChoiceApp.Bi.Student.getStudentsNotInExamRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Student")]
    public partial class getStudentsNotInExamRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int examId;
        
        public getStudentsNotInExamRequestBody() {
        }
        
        public getStudentsNotInExamRequestBody(int examId) {
            this.examId = examId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStudentsNotInExamResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getStudentsNotInExamResponse", Namespace="http://peteranh.com/Services/Student", Order=0)]
        public MultipleChoiceApp.Bi.Student.getStudentsNotInExamResponseBody Body;
        
        public getStudentsNotInExamResponse() {
        }
        
        public getStudentsNotInExamResponse(MultipleChoiceApp.Bi.Student.getStudentsNotInExamResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Student")]
    public partial class getStudentsNotInExamResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Student.Student> getStudentsNotInExamResult;
        
        public getStudentsNotInExamResponseBody() {
        }
        
        public getStudentsNotInExamResponseBody(System.Collections.Generic.List<MultipleChoiceApp.Bi.Student.Student> getStudentsNotInExamResult) {
            this.getStudentsNotInExamResult = getStudentsNotInExamResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStudentInExamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getStudentInExam", Namespace="http://peteranh.com/Services/Student", Order=0)]
        public MultipleChoiceApp.Bi.Student.getStudentInExamRequestBody Body;
        
        public getStudentInExamRequest() {
        }
        
        public getStudentInExamRequest(MultipleChoiceApp.Bi.Student.getStudentInExamRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Student")]
    public partial class getStudentInExamRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int examId;
        
        public getStudentInExamRequestBody() {
        }
        
        public getStudentInExamRequestBody(int examId) {
            this.examId = examId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStudentInExamResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getStudentInExamResponse", Namespace="http://peteranh.com/Services/Student", Order=0)]
        public MultipleChoiceApp.Bi.Student.getStudentInExamResponseBody Body;
        
        public getStudentInExamResponse() {
        }
        
        public getStudentInExamResponse(MultipleChoiceApp.Bi.Student.getStudentInExamResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Student")]
    public partial class getStudentInExamResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Student.Student> getStudentInExamResult;
        
        public getStudentInExamResponseBody() {
        }
        
        public getStudentInExamResponseBody(System.Collections.Generic.List<MultipleChoiceApp.Bi.Student.Student> getStudentInExamResult) {
            this.getStudentInExamResult = getStudentInExamResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addStudentsToExamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addStudentsToExam", Namespace="http://peteranh.com/Services/Student", Order=0)]
        public MultipleChoiceApp.Bi.Student.addStudentsToExamRequestBody Body;
        
        public addStudentsToExamRequest() {
        }
        
        public addStudentsToExamRequest(MultipleChoiceApp.Bi.Student.addStudentsToExamRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Student")]
    public partial class addStudentsToExamRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MultipleChoiceApp.Bi.Student.ArrayOfInt studentIds;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int examId;
        
        public addStudentsToExamRequestBody() {
        }
        
        public addStudentsToExamRequestBody(MultipleChoiceApp.Bi.Student.ArrayOfInt studentIds, int examId) {
            this.studentIds = studentIds;
            this.examId = examId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addStudentsToExamResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addStudentsToExamResponse", Namespace="http://peteranh.com/Services/Student", Order=0)]
        public MultipleChoiceApp.Bi.Student.addStudentsToExamResponseBody Body;
        
        public addStudentsToExamResponse() {
        }
        
        public addStudentsToExamResponse(MultipleChoiceApp.Bi.Student.addStudentsToExamResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Student")]
    public partial class addStudentsToExamResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int addStudentsToExamResult;
        
        public addStudentsToExamResponseBody() {
        }
        
        public addStudentsToExamResponseBody(int addStudentsToExamResult) {
            this.addStudentsToExamResult = addStudentsToExamResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class removeStudentsFromExamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="removeStudentsFromExam", Namespace="http://peteranh.com/Services/Student", Order=0)]
        public MultipleChoiceApp.Bi.Student.removeStudentsFromExamRequestBody Body;
        
        public removeStudentsFromExamRequest() {
        }
        
        public removeStudentsFromExamRequest(MultipleChoiceApp.Bi.Student.removeStudentsFromExamRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Student")]
    public partial class removeStudentsFromExamRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MultipleChoiceApp.Bi.Student.ArrayOfInt studentIds;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int examId;
        
        public removeStudentsFromExamRequestBody() {
        }
        
        public removeStudentsFromExamRequestBody(MultipleChoiceApp.Bi.Student.ArrayOfInt studentIds, int examId) {
            this.studentIds = studentIds;
            this.examId = examId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class removeStudentsFromExamResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="removeStudentsFromExamResponse", Namespace="http://peteranh.com/Services/Student", Order=0)]
        public MultipleChoiceApp.Bi.Student.removeStudentsFromExamResponseBody Body;
        
        public removeStudentsFromExamResponse() {
        }
        
        public removeStudentsFromExamResponse(MultipleChoiceApp.Bi.Student.removeStudentsFromExamResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Student")]
    public partial class removeStudentsFromExamResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int removeStudentsFromExamResult;
        
        public removeStudentsFromExamResponseBody() {
        }
        
        public removeStudentsFromExamResponseBody(int removeStudentsFromExamResult) {
            this.removeStudentsFromExamResult = removeStudentsFromExamResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getByCodeAndPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getByCodeAndPassword", Namespace="http://peteranh.com/Services/Student", Order=0)]
        public MultipleChoiceApp.Bi.Student.getByCodeAndPasswordRequestBody Body;
        
        public getByCodeAndPasswordRequest() {
        }
        
        public getByCodeAndPasswordRequest(MultipleChoiceApp.Bi.Student.getByCodeAndPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Student")]
    public partial class getByCodeAndPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public getByCodeAndPasswordRequestBody() {
        }
        
        public getByCodeAndPasswordRequestBody(string id, string password) {
            this.id = id;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getByCodeAndPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getByCodeAndPasswordResponse", Namespace="http://peteranh.com/Services/Student", Order=0)]
        public MultipleChoiceApp.Bi.Student.getByCodeAndPasswordResponseBody Body;
        
        public getByCodeAndPasswordResponse() {
        }
        
        public getByCodeAndPasswordResponse(MultipleChoiceApp.Bi.Student.getByCodeAndPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Student")]
    public partial class getByCodeAndPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MultipleChoiceApp.Bi.Student.Student getByCodeAndPasswordResult;
        
        public getByCodeAndPasswordResponseBody() {
        }
        
        public getByCodeAndPasswordResponseBody(MultipleChoiceApp.Bi.Student.Student getByCodeAndPasswordResult) {
            this.getByCodeAndPasswordResult = getByCodeAndPasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchByKeywordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchByKeyword", Namespace="http://peteranh.com/Services/Student", Order=0)]
        public MultipleChoiceApp.Bi.Student.searchByKeywordRequestBody Body;
        
        public searchByKeywordRequest() {
        }
        
        public searchByKeywordRequest(MultipleChoiceApp.Bi.Student.searchByKeywordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Student")]
    public partial class searchByKeywordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string keyword;
        
        public searchByKeywordRequestBody() {
        }
        
        public searchByKeywordRequestBody(string keyword) {
            this.keyword = keyword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchByKeywordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchByKeywordResponse", Namespace="http://peteranh.com/Services/Student", Order=0)]
        public MultipleChoiceApp.Bi.Student.searchByKeywordResponseBody Body;
        
        public searchByKeywordResponse() {
        }
        
        public searchByKeywordResponse(MultipleChoiceApp.Bi.Student.searchByKeywordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Student")]
    public partial class searchByKeywordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Student.Student> searchByKeywordResult;
        
        public searchByKeywordResponseBody() {
        }
        
        public searchByKeywordResponseBody(System.Collections.Generic.List<MultipleChoiceApp.Bi.Student.Student> searchByKeywordResult) {
            this.searchByKeywordResult = searchByKeywordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getByCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getByCode", Namespace="http://peteranh.com/Services/Student", Order=0)]
        public MultipleChoiceApp.Bi.Student.getByCodeRequestBody Body;
        
        public getByCodeRequest() {
        }
        
        public getByCodeRequest(MultipleChoiceApp.Bi.Student.getByCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Student")]
    public partial class getByCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string code;
        
        public getByCodeRequestBody() {
        }
        
        public getByCodeRequestBody(string code) {
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getByCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getByCodeResponse", Namespace="http://peteranh.com/Services/Student", Order=0)]
        public MultipleChoiceApp.Bi.Student.getByCodeResponseBody Body;
        
        public getByCodeResponse() {
        }
        
        public getByCodeResponse(MultipleChoiceApp.Bi.Student.getByCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Student")]
    public partial class getByCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MultipleChoiceApp.Bi.Student.Student getByCodeResult;
        
        public getByCodeResponseBody() {
        }
        
        public getByCodeResponseBody(MultipleChoiceApp.Bi.Student.Student getByCodeResult) {
            this.getByCodeResult = getByCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllForSelectDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllForSelectData", Namespace="http://peteranh.com/Services/Student", Order=0)]
        public MultipleChoiceApp.Bi.Student.getAllForSelectDataRequestBody Body;
        
        public getAllForSelectDataRequest() {
        }
        
        public getAllForSelectDataRequest(MultipleChoiceApp.Bi.Student.getAllForSelectDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getAllForSelectDataRequestBody {
        
        public getAllForSelectDataRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllForSelectDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllForSelectDataResponse", Namespace="http://peteranh.com/Services/Student", Order=0)]
        public MultipleChoiceApp.Bi.Student.getAllForSelectDataResponseBody Body;
        
        public getAllForSelectDataResponse() {
        }
        
        public getAllForSelectDataResponse(MultipleChoiceApp.Bi.Student.getAllForSelectDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Student")]
    public partial class getAllForSelectDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Student.Student> getAllForSelectDataResult;
        
        public getAllForSelectDataResponseBody() {
        }
        
        public getAllForSelectDataResponseBody(System.Collections.Generic.List<MultipleChoiceApp.Bi.Student.Student> getAllForSelectDataResult) {
            this.getAllForSelectDataResult = getAllForSelectDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAll", Namespace="http://peteranh.com/Services/Student", Order=0)]
        public MultipleChoiceApp.Bi.Student.getAllRequestBody Body;
        
        public getAllRequest() {
        }
        
        public getAllRequest(MultipleChoiceApp.Bi.Student.getAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Student")]
    public partial class getAllRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int itemsPerPage;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int currentPage;
        
        public getAllRequestBody() {
        }
        
        public getAllRequestBody(int itemsPerPage, int currentPage) {
            this.itemsPerPage = itemsPerPage;
            this.currentPage = currentPage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllResponse", Namespace="http://peteranh.com/Services/Student", Order=0)]
        public MultipleChoiceApp.Bi.Student.getAllResponseBody Body;
        
        public getAllResponse() {
        }
        
        public getAllResponse(MultipleChoiceApp.Bi.Student.getAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Student")]
    public partial class getAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Student.Student> getAllResult;
        
        public getAllResponseBody() {
        }
        
        public getAllResponseBody(System.Collections.Generic.List<MultipleChoiceApp.Bi.Student.Student> getAllResult) {
            this.getAllResult = getAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDetailsByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDetailsById", Namespace="http://peteranh.com/Services/Student", Order=0)]
        public MultipleChoiceApp.Bi.Student.getDetailsByIdRequestBody Body;
        
        public getDetailsByIdRequest() {
        }
        
        public getDetailsByIdRequest(MultipleChoiceApp.Bi.Student.getDetailsByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Student")]
    public partial class getDetailsByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public getDetailsByIdRequestBody() {
        }
        
        public getDetailsByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDetailsByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDetailsByIdResponse", Namespace="http://peteranh.com/Services/Student", Order=0)]
        public MultipleChoiceApp.Bi.Student.getDetailsByIdResponseBody Body;
        
        public getDetailsByIdResponse() {
        }
        
        public getDetailsByIdResponse(MultipleChoiceApp.Bi.Student.getDetailsByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Student")]
    public partial class getDetailsByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MultipleChoiceApp.Bi.Student.Student getDetailsByIdResult;
        
        public getDetailsByIdResponseBody() {
        }
        
        public getDetailsByIdResponseBody(MultipleChoiceApp.Bi.Student.Student getDetailsByIdResult) {
            this.getDetailsByIdResult = getDetailsByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="add", Namespace="http://peteranh.com/Services/Student", Order=0)]
        public MultipleChoiceApp.Bi.Student.addRequestBody Body;
        
        public addRequest() {
        }
        
        public addRequest(MultipleChoiceApp.Bi.Student.addRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Student")]
    public partial class addRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MultipleChoiceApp.Bi.Student.Student item;
        
        public addRequestBody() {
        }
        
        public addRequestBody(MultipleChoiceApp.Bi.Student.Student item) {
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addResponse", Namespace="http://peteranh.com/Services/Student", Order=0)]
        public MultipleChoiceApp.Bi.Student.addResponseBody Body;
        
        public addResponse() {
        }
        
        public addResponse(MultipleChoiceApp.Bi.Student.addResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Student")]
    public partial class addResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool addResult;
        
        public addResponseBody() {
        }
        
        public addResponseBody(bool addResult) {
            this.addResult = addResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addManyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addMany", Namespace="http://peteranh.com/Services/Student", Order=0)]
        public MultipleChoiceApp.Bi.Student.addManyRequestBody Body;
        
        public addManyRequest() {
        }
        
        public addManyRequest(MultipleChoiceApp.Bi.Student.addManyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Student")]
    public partial class addManyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Student.Student> list;
        
        public addManyRequestBody() {
        }
        
        public addManyRequestBody(System.Collections.Generic.List<MultipleChoiceApp.Bi.Student.Student> list) {
            this.list = list;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addManyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addManyResponse", Namespace="http://peteranh.com/Services/Student", Order=0)]
        public MultipleChoiceApp.Bi.Student.addManyResponseBody Body;
        
        public addManyResponse() {
        }
        
        public addManyResponse(MultipleChoiceApp.Bi.Student.addManyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Student")]
    public partial class addManyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int addManyResult;
        
        public addManyResponseBody() {
        }
        
        public addManyResponseBody(int addManyResult) {
            this.addManyResult = addManyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="update", Namespace="http://peteranh.com/Services/Student", Order=0)]
        public MultipleChoiceApp.Bi.Student.updateRequestBody Body;
        
        public updateRequest() {
        }
        
        public updateRequest(MultipleChoiceApp.Bi.Student.updateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Student")]
    public partial class updateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MultipleChoiceApp.Bi.Student.Student item;
        
        public updateRequestBody() {
        }
        
        public updateRequestBody(MultipleChoiceApp.Bi.Student.Student item) {
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateResponse", Namespace="http://peteranh.com/Services/Student", Order=0)]
        public MultipleChoiceApp.Bi.Student.updateResponseBody Body;
        
        public updateResponse() {
        }
        
        public updateResponse(MultipleChoiceApp.Bi.Student.updateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Student")]
    public partial class updateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool updateResult;
        
        public updateResponseBody() {
        }
        
        public updateResponseBody(bool updateResult) {
            this.updateResult = updateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StudentServiceSoapChannel : MultipleChoiceApp.Bi.Student.StudentServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentServiceSoapClient : System.ServiceModel.ClientBase<MultipleChoiceApp.Bi.Student.StudentServiceSoap>, MultipleChoiceApp.Bi.Student.StudentServiceSoap {
        
        public StudentServiceSoapClient() {
        }
        
        public StudentServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Student.setStudentsForExamResponse MultipleChoiceApp.Bi.Student.StudentServiceSoap.setStudentsForExam(MultipleChoiceApp.Bi.Student.setStudentsForExamRequest request) {
            return base.Channel.setStudentsForExam(request);
        }
        
        public int setStudentsForExam(MultipleChoiceApp.Bi.Student.ArrayOfInt studentIds, int examId) {
            MultipleChoiceApp.Bi.Student.setStudentsForExamRequest inValue = new MultipleChoiceApp.Bi.Student.setStudentsForExamRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Student.setStudentsForExamRequestBody();
            inValue.Body.studentIds = studentIds;
            inValue.Body.examId = examId;
            MultipleChoiceApp.Bi.Student.setStudentsForExamResponse retVal = ((MultipleChoiceApp.Bi.Student.StudentServiceSoap)(this)).setStudentsForExam(inValue);
            return retVal.Body.setStudentsForExamResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.setStudentsForExamResponse> MultipleChoiceApp.Bi.Student.StudentServiceSoap.setStudentsForExamAsync(MultipleChoiceApp.Bi.Student.setStudentsForExamRequest request) {
            return base.Channel.setStudentsForExamAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.setStudentsForExamResponse> setStudentsForExamAsync(MultipleChoiceApp.Bi.Student.ArrayOfInt studentIds, int examId) {
            MultipleChoiceApp.Bi.Student.setStudentsForExamRequest inValue = new MultipleChoiceApp.Bi.Student.setStudentsForExamRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Student.setStudentsForExamRequestBody();
            inValue.Body.studentIds = studentIds;
            inValue.Body.examId = examId;
            return ((MultipleChoiceApp.Bi.Student.StudentServiceSoap)(this)).setStudentsForExamAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Student.getStudentsNotInExamResponse MultipleChoiceApp.Bi.Student.StudentServiceSoap.getStudentsNotInExam(MultipleChoiceApp.Bi.Student.getStudentsNotInExamRequest request) {
            return base.Channel.getStudentsNotInExam(request);
        }
        
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Student.Student> getStudentsNotInExam(int examId) {
            MultipleChoiceApp.Bi.Student.getStudentsNotInExamRequest inValue = new MultipleChoiceApp.Bi.Student.getStudentsNotInExamRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Student.getStudentsNotInExamRequestBody();
            inValue.Body.examId = examId;
            MultipleChoiceApp.Bi.Student.getStudentsNotInExamResponse retVal = ((MultipleChoiceApp.Bi.Student.StudentServiceSoap)(this)).getStudentsNotInExam(inValue);
            return retVal.Body.getStudentsNotInExamResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.getStudentsNotInExamResponse> MultipleChoiceApp.Bi.Student.StudentServiceSoap.getStudentsNotInExamAsync(MultipleChoiceApp.Bi.Student.getStudentsNotInExamRequest request) {
            return base.Channel.getStudentsNotInExamAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.getStudentsNotInExamResponse> getStudentsNotInExamAsync(int examId) {
            MultipleChoiceApp.Bi.Student.getStudentsNotInExamRequest inValue = new MultipleChoiceApp.Bi.Student.getStudentsNotInExamRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Student.getStudentsNotInExamRequestBody();
            inValue.Body.examId = examId;
            return ((MultipleChoiceApp.Bi.Student.StudentServiceSoap)(this)).getStudentsNotInExamAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Student.getStudentInExamResponse MultipleChoiceApp.Bi.Student.StudentServiceSoap.getStudentInExam(MultipleChoiceApp.Bi.Student.getStudentInExamRequest request) {
            return base.Channel.getStudentInExam(request);
        }
        
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Student.Student> getStudentInExam(int examId) {
            MultipleChoiceApp.Bi.Student.getStudentInExamRequest inValue = new MultipleChoiceApp.Bi.Student.getStudentInExamRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Student.getStudentInExamRequestBody();
            inValue.Body.examId = examId;
            MultipleChoiceApp.Bi.Student.getStudentInExamResponse retVal = ((MultipleChoiceApp.Bi.Student.StudentServiceSoap)(this)).getStudentInExam(inValue);
            return retVal.Body.getStudentInExamResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.getStudentInExamResponse> MultipleChoiceApp.Bi.Student.StudentServiceSoap.getStudentInExamAsync(MultipleChoiceApp.Bi.Student.getStudentInExamRequest request) {
            return base.Channel.getStudentInExamAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.getStudentInExamResponse> getStudentInExamAsync(int examId) {
            MultipleChoiceApp.Bi.Student.getStudentInExamRequest inValue = new MultipleChoiceApp.Bi.Student.getStudentInExamRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Student.getStudentInExamRequestBody();
            inValue.Body.examId = examId;
            return ((MultipleChoiceApp.Bi.Student.StudentServiceSoap)(this)).getStudentInExamAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Student.addStudentsToExamResponse MultipleChoiceApp.Bi.Student.StudentServiceSoap.addStudentsToExam(MultipleChoiceApp.Bi.Student.addStudentsToExamRequest request) {
            return base.Channel.addStudentsToExam(request);
        }
        
        public int addStudentsToExam(MultipleChoiceApp.Bi.Student.ArrayOfInt studentIds, int examId) {
            MultipleChoiceApp.Bi.Student.addStudentsToExamRequest inValue = new MultipleChoiceApp.Bi.Student.addStudentsToExamRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Student.addStudentsToExamRequestBody();
            inValue.Body.studentIds = studentIds;
            inValue.Body.examId = examId;
            MultipleChoiceApp.Bi.Student.addStudentsToExamResponse retVal = ((MultipleChoiceApp.Bi.Student.StudentServiceSoap)(this)).addStudentsToExam(inValue);
            return retVal.Body.addStudentsToExamResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.addStudentsToExamResponse> MultipleChoiceApp.Bi.Student.StudentServiceSoap.addStudentsToExamAsync(MultipleChoiceApp.Bi.Student.addStudentsToExamRequest request) {
            return base.Channel.addStudentsToExamAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.addStudentsToExamResponse> addStudentsToExamAsync(MultipleChoiceApp.Bi.Student.ArrayOfInt studentIds, int examId) {
            MultipleChoiceApp.Bi.Student.addStudentsToExamRequest inValue = new MultipleChoiceApp.Bi.Student.addStudentsToExamRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Student.addStudentsToExamRequestBody();
            inValue.Body.studentIds = studentIds;
            inValue.Body.examId = examId;
            return ((MultipleChoiceApp.Bi.Student.StudentServiceSoap)(this)).addStudentsToExamAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Student.removeStudentsFromExamResponse MultipleChoiceApp.Bi.Student.StudentServiceSoap.removeStudentsFromExam(MultipleChoiceApp.Bi.Student.removeStudentsFromExamRequest request) {
            return base.Channel.removeStudentsFromExam(request);
        }
        
        public int removeStudentsFromExam(MultipleChoiceApp.Bi.Student.ArrayOfInt studentIds, int examId) {
            MultipleChoiceApp.Bi.Student.removeStudentsFromExamRequest inValue = new MultipleChoiceApp.Bi.Student.removeStudentsFromExamRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Student.removeStudentsFromExamRequestBody();
            inValue.Body.studentIds = studentIds;
            inValue.Body.examId = examId;
            MultipleChoiceApp.Bi.Student.removeStudentsFromExamResponse retVal = ((MultipleChoiceApp.Bi.Student.StudentServiceSoap)(this)).removeStudentsFromExam(inValue);
            return retVal.Body.removeStudentsFromExamResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.removeStudentsFromExamResponse> MultipleChoiceApp.Bi.Student.StudentServiceSoap.removeStudentsFromExamAsync(MultipleChoiceApp.Bi.Student.removeStudentsFromExamRequest request) {
            return base.Channel.removeStudentsFromExamAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.removeStudentsFromExamResponse> removeStudentsFromExamAsync(MultipleChoiceApp.Bi.Student.ArrayOfInt studentIds, int examId) {
            MultipleChoiceApp.Bi.Student.removeStudentsFromExamRequest inValue = new MultipleChoiceApp.Bi.Student.removeStudentsFromExamRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Student.removeStudentsFromExamRequestBody();
            inValue.Body.studentIds = studentIds;
            inValue.Body.examId = examId;
            return ((MultipleChoiceApp.Bi.Student.StudentServiceSoap)(this)).removeStudentsFromExamAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Student.getByCodeAndPasswordResponse MultipleChoiceApp.Bi.Student.StudentServiceSoap.getByCodeAndPassword(MultipleChoiceApp.Bi.Student.getByCodeAndPasswordRequest request) {
            return base.Channel.getByCodeAndPassword(request);
        }
        
        public MultipleChoiceApp.Bi.Student.Student getByCodeAndPassword(string id, string password) {
            MultipleChoiceApp.Bi.Student.getByCodeAndPasswordRequest inValue = new MultipleChoiceApp.Bi.Student.getByCodeAndPasswordRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Student.getByCodeAndPasswordRequestBody();
            inValue.Body.id = id;
            inValue.Body.password = password;
            MultipleChoiceApp.Bi.Student.getByCodeAndPasswordResponse retVal = ((MultipleChoiceApp.Bi.Student.StudentServiceSoap)(this)).getByCodeAndPassword(inValue);
            return retVal.Body.getByCodeAndPasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.getByCodeAndPasswordResponse> MultipleChoiceApp.Bi.Student.StudentServiceSoap.getByCodeAndPasswordAsync(MultipleChoiceApp.Bi.Student.getByCodeAndPasswordRequest request) {
            return base.Channel.getByCodeAndPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.getByCodeAndPasswordResponse> getByCodeAndPasswordAsync(string id, string password) {
            MultipleChoiceApp.Bi.Student.getByCodeAndPasswordRequest inValue = new MultipleChoiceApp.Bi.Student.getByCodeAndPasswordRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Student.getByCodeAndPasswordRequestBody();
            inValue.Body.id = id;
            inValue.Body.password = password;
            return ((MultipleChoiceApp.Bi.Student.StudentServiceSoap)(this)).getByCodeAndPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Student.searchByKeywordResponse MultipleChoiceApp.Bi.Student.StudentServiceSoap.searchByKeyword(MultipleChoiceApp.Bi.Student.searchByKeywordRequest request) {
            return base.Channel.searchByKeyword(request);
        }
        
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Student.Student> searchByKeyword(string keyword) {
            MultipleChoiceApp.Bi.Student.searchByKeywordRequest inValue = new MultipleChoiceApp.Bi.Student.searchByKeywordRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Student.searchByKeywordRequestBody();
            inValue.Body.keyword = keyword;
            MultipleChoiceApp.Bi.Student.searchByKeywordResponse retVal = ((MultipleChoiceApp.Bi.Student.StudentServiceSoap)(this)).searchByKeyword(inValue);
            return retVal.Body.searchByKeywordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.searchByKeywordResponse> MultipleChoiceApp.Bi.Student.StudentServiceSoap.searchByKeywordAsync(MultipleChoiceApp.Bi.Student.searchByKeywordRequest request) {
            return base.Channel.searchByKeywordAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.searchByKeywordResponse> searchByKeywordAsync(string keyword) {
            MultipleChoiceApp.Bi.Student.searchByKeywordRequest inValue = new MultipleChoiceApp.Bi.Student.searchByKeywordRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Student.searchByKeywordRequestBody();
            inValue.Body.keyword = keyword;
            return ((MultipleChoiceApp.Bi.Student.StudentServiceSoap)(this)).searchByKeywordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Student.getByCodeResponse MultipleChoiceApp.Bi.Student.StudentServiceSoap.getByCode(MultipleChoiceApp.Bi.Student.getByCodeRequest request) {
            return base.Channel.getByCode(request);
        }
        
        public MultipleChoiceApp.Bi.Student.Student getByCode(string code) {
            MultipleChoiceApp.Bi.Student.getByCodeRequest inValue = new MultipleChoiceApp.Bi.Student.getByCodeRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Student.getByCodeRequestBody();
            inValue.Body.code = code;
            MultipleChoiceApp.Bi.Student.getByCodeResponse retVal = ((MultipleChoiceApp.Bi.Student.StudentServiceSoap)(this)).getByCode(inValue);
            return retVal.Body.getByCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.getByCodeResponse> MultipleChoiceApp.Bi.Student.StudentServiceSoap.getByCodeAsync(MultipleChoiceApp.Bi.Student.getByCodeRequest request) {
            return base.Channel.getByCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.getByCodeResponse> getByCodeAsync(string code) {
            MultipleChoiceApp.Bi.Student.getByCodeRequest inValue = new MultipleChoiceApp.Bi.Student.getByCodeRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Student.getByCodeRequestBody();
            inValue.Body.code = code;
            return ((MultipleChoiceApp.Bi.Student.StudentServiceSoap)(this)).getByCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Student.getAllForSelectDataResponse MultipleChoiceApp.Bi.Student.StudentServiceSoap.getAllForSelectData(MultipleChoiceApp.Bi.Student.getAllForSelectDataRequest request) {
            return base.Channel.getAllForSelectData(request);
        }
        
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Student.Student> getAllForSelectData() {
            MultipleChoiceApp.Bi.Student.getAllForSelectDataRequest inValue = new MultipleChoiceApp.Bi.Student.getAllForSelectDataRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Student.getAllForSelectDataRequestBody();
            MultipleChoiceApp.Bi.Student.getAllForSelectDataResponse retVal = ((MultipleChoiceApp.Bi.Student.StudentServiceSoap)(this)).getAllForSelectData(inValue);
            return retVal.Body.getAllForSelectDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.getAllForSelectDataResponse> MultipleChoiceApp.Bi.Student.StudentServiceSoap.getAllForSelectDataAsync(MultipleChoiceApp.Bi.Student.getAllForSelectDataRequest request) {
            return base.Channel.getAllForSelectDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.getAllForSelectDataResponse> getAllForSelectDataAsync() {
            MultipleChoiceApp.Bi.Student.getAllForSelectDataRequest inValue = new MultipleChoiceApp.Bi.Student.getAllForSelectDataRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Student.getAllForSelectDataRequestBody();
            return ((MultipleChoiceApp.Bi.Student.StudentServiceSoap)(this)).getAllForSelectDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Student.getAllResponse MultipleChoiceApp.Bi.Student.StudentServiceSoap.getAll(MultipleChoiceApp.Bi.Student.getAllRequest request) {
            return base.Channel.getAll(request);
        }
        
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Student.Student> getAll(int itemsPerPage, int currentPage) {
            MultipleChoiceApp.Bi.Student.getAllRequest inValue = new MultipleChoiceApp.Bi.Student.getAllRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Student.getAllRequestBody();
            inValue.Body.itemsPerPage = itemsPerPage;
            inValue.Body.currentPage = currentPage;
            MultipleChoiceApp.Bi.Student.getAllResponse retVal = ((MultipleChoiceApp.Bi.Student.StudentServiceSoap)(this)).getAll(inValue);
            return retVal.Body.getAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.getAllResponse> MultipleChoiceApp.Bi.Student.StudentServiceSoap.getAllAsync(MultipleChoiceApp.Bi.Student.getAllRequest request) {
            return base.Channel.getAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.getAllResponse> getAllAsync(int itemsPerPage, int currentPage) {
            MultipleChoiceApp.Bi.Student.getAllRequest inValue = new MultipleChoiceApp.Bi.Student.getAllRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Student.getAllRequestBody();
            inValue.Body.itemsPerPage = itemsPerPage;
            inValue.Body.currentPage = currentPage;
            return ((MultipleChoiceApp.Bi.Student.StudentServiceSoap)(this)).getAllAsync(inValue);
        }
        
        public int countAll() {
            return base.Channel.countAll();
        }
        
        public System.Threading.Tasks.Task<int> countAllAsync() {
            return base.Channel.countAllAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Student.getDetailsByIdResponse MultipleChoiceApp.Bi.Student.StudentServiceSoap.getDetailsById(MultipleChoiceApp.Bi.Student.getDetailsByIdRequest request) {
            return base.Channel.getDetailsById(request);
        }
        
        public MultipleChoiceApp.Bi.Student.Student getDetailsById(int id) {
            MultipleChoiceApp.Bi.Student.getDetailsByIdRequest inValue = new MultipleChoiceApp.Bi.Student.getDetailsByIdRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Student.getDetailsByIdRequestBody();
            inValue.Body.id = id;
            MultipleChoiceApp.Bi.Student.getDetailsByIdResponse retVal = ((MultipleChoiceApp.Bi.Student.StudentServiceSoap)(this)).getDetailsById(inValue);
            return retVal.Body.getDetailsByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.getDetailsByIdResponse> MultipleChoiceApp.Bi.Student.StudentServiceSoap.getDetailsByIdAsync(MultipleChoiceApp.Bi.Student.getDetailsByIdRequest request) {
            return base.Channel.getDetailsByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.getDetailsByIdResponse> getDetailsByIdAsync(int id) {
            MultipleChoiceApp.Bi.Student.getDetailsByIdRequest inValue = new MultipleChoiceApp.Bi.Student.getDetailsByIdRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Student.getDetailsByIdRequestBody();
            inValue.Body.id = id;
            return ((MultipleChoiceApp.Bi.Student.StudentServiceSoap)(this)).getDetailsByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Student.addResponse MultipleChoiceApp.Bi.Student.StudentServiceSoap.add(MultipleChoiceApp.Bi.Student.addRequest request) {
            return base.Channel.add(request);
        }
        
        public bool add(MultipleChoiceApp.Bi.Student.Student item) {
            MultipleChoiceApp.Bi.Student.addRequest inValue = new MultipleChoiceApp.Bi.Student.addRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Student.addRequestBody();
            inValue.Body.item = item;
            MultipleChoiceApp.Bi.Student.addResponse retVal = ((MultipleChoiceApp.Bi.Student.StudentServiceSoap)(this)).add(inValue);
            return retVal.Body.addResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.addResponse> MultipleChoiceApp.Bi.Student.StudentServiceSoap.addAsync(MultipleChoiceApp.Bi.Student.addRequest request) {
            return base.Channel.addAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.addResponse> addAsync(MultipleChoiceApp.Bi.Student.Student item) {
            MultipleChoiceApp.Bi.Student.addRequest inValue = new MultipleChoiceApp.Bi.Student.addRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Student.addRequestBody();
            inValue.Body.item = item;
            return ((MultipleChoiceApp.Bi.Student.StudentServiceSoap)(this)).addAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Student.addManyResponse MultipleChoiceApp.Bi.Student.StudentServiceSoap.addMany(MultipleChoiceApp.Bi.Student.addManyRequest request) {
            return base.Channel.addMany(request);
        }
        
        public int addMany(System.Collections.Generic.List<MultipleChoiceApp.Bi.Student.Student> list) {
            MultipleChoiceApp.Bi.Student.addManyRequest inValue = new MultipleChoiceApp.Bi.Student.addManyRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Student.addManyRequestBody();
            inValue.Body.list = list;
            MultipleChoiceApp.Bi.Student.addManyResponse retVal = ((MultipleChoiceApp.Bi.Student.StudentServiceSoap)(this)).addMany(inValue);
            return retVal.Body.addManyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.addManyResponse> MultipleChoiceApp.Bi.Student.StudentServiceSoap.addManyAsync(MultipleChoiceApp.Bi.Student.addManyRequest request) {
            return base.Channel.addManyAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.addManyResponse> addManyAsync(System.Collections.Generic.List<MultipleChoiceApp.Bi.Student.Student> list) {
            MultipleChoiceApp.Bi.Student.addManyRequest inValue = new MultipleChoiceApp.Bi.Student.addManyRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Student.addManyRequestBody();
            inValue.Body.list = list;
            return ((MultipleChoiceApp.Bi.Student.StudentServiceSoap)(this)).addManyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Student.updateResponse MultipleChoiceApp.Bi.Student.StudentServiceSoap.update(MultipleChoiceApp.Bi.Student.updateRequest request) {
            return base.Channel.update(request);
        }
        
        public bool update(MultipleChoiceApp.Bi.Student.Student item) {
            MultipleChoiceApp.Bi.Student.updateRequest inValue = new MultipleChoiceApp.Bi.Student.updateRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Student.updateRequestBody();
            inValue.Body.item = item;
            MultipleChoiceApp.Bi.Student.updateResponse retVal = ((MultipleChoiceApp.Bi.Student.StudentServiceSoap)(this)).update(inValue);
            return retVal.Body.updateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.updateResponse> MultipleChoiceApp.Bi.Student.StudentServiceSoap.updateAsync(MultipleChoiceApp.Bi.Student.updateRequest request) {
            return base.Channel.updateAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Student.updateResponse> updateAsync(MultipleChoiceApp.Bi.Student.Student item) {
            MultipleChoiceApp.Bi.Student.updateRequest inValue = new MultipleChoiceApp.Bi.Student.updateRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Student.updateRequestBody();
            inValue.Body.item = item;
            return ((MultipleChoiceApp.Bi.Student.StudentServiceSoap)(this)).updateAsync(inValue);
        }
        
        public bool delete(int id) {
            return base.Channel.delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> deleteAsync(int id) {
            return base.Channel.deleteAsync(id);
        }
    }
}
