//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultipleChoiceApp.Bi.Subject {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Subject", Namespace="http://peteranh.com/Services/Subject")]
    [System.SerializableAttribute()]
    public partial class Subject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private int TotalQuestionField;
        
        private int DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LecturerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int TotalQuestion {
            get {
                return this.TotalQuestionField;
            }
            set {
                if ((this.TotalQuestionField.Equals(value) != true)) {
                    this.TotalQuestionField = value;
                    this.RaisePropertyChanged("TotalQuestion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Lecturer {
            get {
                return this.LecturerField;
            }
            set {
                if ((object.ReferenceEquals(this.LecturerField, value) != true)) {
                    this.LecturerField = value;
                    this.RaisePropertyChanged("Lecturer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://peteranh.com/Services/Subject", ConfigurationName="Bi.Subject.SubjectServiceSoap")]
    public interface SubjectServiceSoap {
        
        // CODEGEN: Generating message contract since element name getAvailableForExamResult from namespace http://peteranh.com/Services/Subject is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Subject/getAvailableForExam", ReplyAction="*")]
        MultipleChoiceApp.Bi.Subject.getAvailableForExamResponse getAvailableForExam(MultipleChoiceApp.Bi.Subject.getAvailableForExamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Subject/getAvailableForExam", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Subject.getAvailableForExamResponse> getAvailableForExamAsync(MultipleChoiceApp.Bi.Subject.getAvailableForExamRequest request);
        
        // CODEGEN: Generating message contract since element name keyword from namespace http://peteranh.com/Services/Subject is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Subject/searchByKeyword", ReplyAction="*")]
        MultipleChoiceApp.Bi.Subject.searchByKeywordResponse searchByKeyword(MultipleChoiceApp.Bi.Subject.searchByKeywordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Subject/searchByKeyword", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Subject.searchByKeywordResponse> searchByKeywordAsync(MultipleChoiceApp.Bi.Subject.searchByKeywordRequest request);
        
        // CODEGEN: Generating message contract since element name getAllForSelectDataResult from namespace http://peteranh.com/Services/Subject is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Subject/getAllForSelectData", ReplyAction="*")]
        MultipleChoiceApp.Bi.Subject.getAllForSelectDataResponse getAllForSelectData(MultipleChoiceApp.Bi.Subject.getAllForSelectDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Subject/getAllForSelectData", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Subject.getAllForSelectDataResponse> getAllForSelectDataAsync(MultipleChoiceApp.Bi.Subject.getAllForSelectDataRequest request);
        
        // CODEGEN: Generating message contract since element name getAllResult from namespace http://peteranh.com/Services/Subject is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Subject/getAll", ReplyAction="*")]
        MultipleChoiceApp.Bi.Subject.getAllResponse getAll(MultipleChoiceApp.Bi.Subject.getAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Subject/getAll", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Subject.getAllResponse> getAllAsync(MultipleChoiceApp.Bi.Subject.getAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Subject/countAll", ReplyAction="*")]
        int countAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Subject/countAll", ReplyAction="*")]
        System.Threading.Tasks.Task<int> countAllAsync();
        
        // CODEGEN: Generating message contract since element name getDetailsByIdResult from namespace http://peteranh.com/Services/Subject is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Subject/getDetailsById", ReplyAction="*")]
        MultipleChoiceApp.Bi.Subject.getDetailsByIdResponse getDetailsById(MultipleChoiceApp.Bi.Subject.getDetailsByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Subject/getDetailsById", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Subject.getDetailsByIdResponse> getDetailsByIdAsync(MultipleChoiceApp.Bi.Subject.getDetailsByIdRequest request);
        
        // CODEGEN: Generating message contract since element name item from namespace http://peteranh.com/Services/Subject is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Subject/add", ReplyAction="*")]
        MultipleChoiceApp.Bi.Subject.addResponse add(MultipleChoiceApp.Bi.Subject.addRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Subject/add", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Subject.addResponse> addAsync(MultipleChoiceApp.Bi.Subject.addRequest request);
        
        // CODEGEN: Generating message contract since element name list from namespace http://peteranh.com/Services/Subject is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Subject/addMany", ReplyAction="*")]
        MultipleChoiceApp.Bi.Subject.addManyResponse addMany(MultipleChoiceApp.Bi.Subject.addManyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Subject/addMany", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Subject.addManyResponse> addManyAsync(MultipleChoiceApp.Bi.Subject.addManyRequest request);
        
        // CODEGEN: Generating message contract since element name item from namespace http://peteranh.com/Services/Subject is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Subject/update", ReplyAction="*")]
        MultipleChoiceApp.Bi.Subject.updateResponse update(MultipleChoiceApp.Bi.Subject.updateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Subject/update", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Subject.updateResponse> updateAsync(MultipleChoiceApp.Bi.Subject.updateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Subject/delete", ReplyAction="*")]
        bool delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Subject/delete", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> deleteAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAvailableForExamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAvailableForExam", Namespace="http://peteranh.com/Services/Subject", Order=0)]
        public MultipleChoiceApp.Bi.Subject.getAvailableForExamRequestBody Body;
        
        public getAvailableForExamRequest() {
        }
        
        public getAvailableForExamRequest(MultipleChoiceApp.Bi.Subject.getAvailableForExamRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Subject")]
    public partial class getAvailableForExamRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime d;
        
        public getAvailableForExamRequestBody() {
        }
        
        public getAvailableForExamRequestBody(System.DateTime d) {
            this.d = d;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAvailableForExamResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAvailableForExamResponse", Namespace="http://peteranh.com/Services/Subject", Order=0)]
        public MultipleChoiceApp.Bi.Subject.getAvailableForExamResponseBody Body;
        
        public getAvailableForExamResponse() {
        }
        
        public getAvailableForExamResponse(MultipleChoiceApp.Bi.Subject.getAvailableForExamResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Subject")]
    public partial class getAvailableForExamResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Subject.Subject> getAvailableForExamResult;
        
        public getAvailableForExamResponseBody() {
        }
        
        public getAvailableForExamResponseBody(System.Collections.Generic.List<MultipleChoiceApp.Bi.Subject.Subject> getAvailableForExamResult) {
            this.getAvailableForExamResult = getAvailableForExamResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchByKeywordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchByKeyword", Namespace="http://peteranh.com/Services/Subject", Order=0)]
        public MultipleChoiceApp.Bi.Subject.searchByKeywordRequestBody Body;
        
        public searchByKeywordRequest() {
        }
        
        public searchByKeywordRequest(MultipleChoiceApp.Bi.Subject.searchByKeywordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Subject")]
    public partial class searchByKeywordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string keyword;
        
        public searchByKeywordRequestBody() {
        }
        
        public searchByKeywordRequestBody(string keyword) {
            this.keyword = keyword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchByKeywordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchByKeywordResponse", Namespace="http://peteranh.com/Services/Subject", Order=0)]
        public MultipleChoiceApp.Bi.Subject.searchByKeywordResponseBody Body;
        
        public searchByKeywordResponse() {
        }
        
        public searchByKeywordResponse(MultipleChoiceApp.Bi.Subject.searchByKeywordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Subject")]
    public partial class searchByKeywordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Subject.Subject> searchByKeywordResult;
        
        public searchByKeywordResponseBody() {
        }
        
        public searchByKeywordResponseBody(System.Collections.Generic.List<MultipleChoiceApp.Bi.Subject.Subject> searchByKeywordResult) {
            this.searchByKeywordResult = searchByKeywordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllForSelectDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllForSelectData", Namespace="http://peteranh.com/Services/Subject", Order=0)]
        public MultipleChoiceApp.Bi.Subject.getAllForSelectDataRequestBody Body;
        
        public getAllForSelectDataRequest() {
        }
        
        public getAllForSelectDataRequest(MultipleChoiceApp.Bi.Subject.getAllForSelectDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getAllForSelectDataRequestBody {
        
        public getAllForSelectDataRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllForSelectDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllForSelectDataResponse", Namespace="http://peteranh.com/Services/Subject", Order=0)]
        public MultipleChoiceApp.Bi.Subject.getAllForSelectDataResponseBody Body;
        
        public getAllForSelectDataResponse() {
        }
        
        public getAllForSelectDataResponse(MultipleChoiceApp.Bi.Subject.getAllForSelectDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Subject")]
    public partial class getAllForSelectDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Subject.Subject> getAllForSelectDataResult;
        
        public getAllForSelectDataResponseBody() {
        }
        
        public getAllForSelectDataResponseBody(System.Collections.Generic.List<MultipleChoiceApp.Bi.Subject.Subject> getAllForSelectDataResult) {
            this.getAllForSelectDataResult = getAllForSelectDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAll", Namespace="http://peteranh.com/Services/Subject", Order=0)]
        public MultipleChoiceApp.Bi.Subject.getAllRequestBody Body;
        
        public getAllRequest() {
        }
        
        public getAllRequest(MultipleChoiceApp.Bi.Subject.getAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Subject")]
    public partial class getAllRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int itemsPerPage;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int currentPage;
        
        public getAllRequestBody() {
        }
        
        public getAllRequestBody(int itemsPerPage, int currentPage) {
            this.itemsPerPage = itemsPerPage;
            this.currentPage = currentPage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllResponse", Namespace="http://peteranh.com/Services/Subject", Order=0)]
        public MultipleChoiceApp.Bi.Subject.getAllResponseBody Body;
        
        public getAllResponse() {
        }
        
        public getAllResponse(MultipleChoiceApp.Bi.Subject.getAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Subject")]
    public partial class getAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Subject.Subject> getAllResult;
        
        public getAllResponseBody() {
        }
        
        public getAllResponseBody(System.Collections.Generic.List<MultipleChoiceApp.Bi.Subject.Subject> getAllResult) {
            this.getAllResult = getAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDetailsByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDetailsById", Namespace="http://peteranh.com/Services/Subject", Order=0)]
        public MultipleChoiceApp.Bi.Subject.getDetailsByIdRequestBody Body;
        
        public getDetailsByIdRequest() {
        }
        
        public getDetailsByIdRequest(MultipleChoiceApp.Bi.Subject.getDetailsByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Subject")]
    public partial class getDetailsByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public getDetailsByIdRequestBody() {
        }
        
        public getDetailsByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDetailsByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDetailsByIdResponse", Namespace="http://peteranh.com/Services/Subject", Order=0)]
        public MultipleChoiceApp.Bi.Subject.getDetailsByIdResponseBody Body;
        
        public getDetailsByIdResponse() {
        }
        
        public getDetailsByIdResponse(MultipleChoiceApp.Bi.Subject.getDetailsByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Subject")]
    public partial class getDetailsByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MultipleChoiceApp.Bi.Subject.Subject getDetailsByIdResult;
        
        public getDetailsByIdResponseBody() {
        }
        
        public getDetailsByIdResponseBody(MultipleChoiceApp.Bi.Subject.Subject getDetailsByIdResult) {
            this.getDetailsByIdResult = getDetailsByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="add", Namespace="http://peteranh.com/Services/Subject", Order=0)]
        public MultipleChoiceApp.Bi.Subject.addRequestBody Body;
        
        public addRequest() {
        }
        
        public addRequest(MultipleChoiceApp.Bi.Subject.addRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Subject")]
    public partial class addRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MultipleChoiceApp.Bi.Subject.Subject item;
        
        public addRequestBody() {
        }
        
        public addRequestBody(MultipleChoiceApp.Bi.Subject.Subject item) {
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addResponse", Namespace="http://peteranh.com/Services/Subject", Order=0)]
        public MultipleChoiceApp.Bi.Subject.addResponseBody Body;
        
        public addResponse() {
        }
        
        public addResponse(MultipleChoiceApp.Bi.Subject.addResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Subject")]
    public partial class addResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool addResult;
        
        public addResponseBody() {
        }
        
        public addResponseBody(bool addResult) {
            this.addResult = addResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addManyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addMany", Namespace="http://peteranh.com/Services/Subject", Order=0)]
        public MultipleChoiceApp.Bi.Subject.addManyRequestBody Body;
        
        public addManyRequest() {
        }
        
        public addManyRequest(MultipleChoiceApp.Bi.Subject.addManyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Subject")]
    public partial class addManyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Subject.Subject> list;
        
        public addManyRequestBody() {
        }
        
        public addManyRequestBody(System.Collections.Generic.List<MultipleChoiceApp.Bi.Subject.Subject> list) {
            this.list = list;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addManyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addManyResponse", Namespace="http://peteranh.com/Services/Subject", Order=0)]
        public MultipleChoiceApp.Bi.Subject.addManyResponseBody Body;
        
        public addManyResponse() {
        }
        
        public addManyResponse(MultipleChoiceApp.Bi.Subject.addManyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Subject")]
    public partial class addManyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int addManyResult;
        
        public addManyResponseBody() {
        }
        
        public addManyResponseBody(int addManyResult) {
            this.addManyResult = addManyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="update", Namespace="http://peteranh.com/Services/Subject", Order=0)]
        public MultipleChoiceApp.Bi.Subject.updateRequestBody Body;
        
        public updateRequest() {
        }
        
        public updateRequest(MultipleChoiceApp.Bi.Subject.updateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Subject")]
    public partial class updateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MultipleChoiceApp.Bi.Subject.Subject item;
        
        public updateRequestBody() {
        }
        
        public updateRequestBody(MultipleChoiceApp.Bi.Subject.Subject item) {
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateResponse", Namespace="http://peteranh.com/Services/Subject", Order=0)]
        public MultipleChoiceApp.Bi.Subject.updateResponseBody Body;
        
        public updateResponse() {
        }
        
        public updateResponse(MultipleChoiceApp.Bi.Subject.updateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Subject")]
    public partial class updateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool updateResult;
        
        public updateResponseBody() {
        }
        
        public updateResponseBody(bool updateResult) {
            this.updateResult = updateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SubjectServiceSoapChannel : MultipleChoiceApp.Bi.Subject.SubjectServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubjectServiceSoapClient : System.ServiceModel.ClientBase<MultipleChoiceApp.Bi.Subject.SubjectServiceSoap>, MultipleChoiceApp.Bi.Subject.SubjectServiceSoap {
        
        public SubjectServiceSoapClient() {
        }
        
        public SubjectServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SubjectServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubjectServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubjectServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Subject.getAvailableForExamResponse MultipleChoiceApp.Bi.Subject.SubjectServiceSoap.getAvailableForExam(MultipleChoiceApp.Bi.Subject.getAvailableForExamRequest request) {
            return base.Channel.getAvailableForExam(request);
        }
        
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Subject.Subject> getAvailableForExam(System.DateTime d) {
            MultipleChoiceApp.Bi.Subject.getAvailableForExamRequest inValue = new MultipleChoiceApp.Bi.Subject.getAvailableForExamRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Subject.getAvailableForExamRequestBody();
            inValue.Body.d = d;
            MultipleChoiceApp.Bi.Subject.getAvailableForExamResponse retVal = ((MultipleChoiceApp.Bi.Subject.SubjectServiceSoap)(this)).getAvailableForExam(inValue);
            return retVal.Body.getAvailableForExamResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Subject.getAvailableForExamResponse> MultipleChoiceApp.Bi.Subject.SubjectServiceSoap.getAvailableForExamAsync(MultipleChoiceApp.Bi.Subject.getAvailableForExamRequest request) {
            return base.Channel.getAvailableForExamAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Subject.getAvailableForExamResponse> getAvailableForExamAsync(System.DateTime d) {
            MultipleChoiceApp.Bi.Subject.getAvailableForExamRequest inValue = new MultipleChoiceApp.Bi.Subject.getAvailableForExamRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Subject.getAvailableForExamRequestBody();
            inValue.Body.d = d;
            return ((MultipleChoiceApp.Bi.Subject.SubjectServiceSoap)(this)).getAvailableForExamAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Subject.searchByKeywordResponse MultipleChoiceApp.Bi.Subject.SubjectServiceSoap.searchByKeyword(MultipleChoiceApp.Bi.Subject.searchByKeywordRequest request) {
            return base.Channel.searchByKeyword(request);
        }
        
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Subject.Subject> searchByKeyword(string keyword) {
            MultipleChoiceApp.Bi.Subject.searchByKeywordRequest inValue = new MultipleChoiceApp.Bi.Subject.searchByKeywordRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Subject.searchByKeywordRequestBody();
            inValue.Body.keyword = keyword;
            MultipleChoiceApp.Bi.Subject.searchByKeywordResponse retVal = ((MultipleChoiceApp.Bi.Subject.SubjectServiceSoap)(this)).searchByKeyword(inValue);
            return retVal.Body.searchByKeywordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Subject.searchByKeywordResponse> MultipleChoiceApp.Bi.Subject.SubjectServiceSoap.searchByKeywordAsync(MultipleChoiceApp.Bi.Subject.searchByKeywordRequest request) {
            return base.Channel.searchByKeywordAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Subject.searchByKeywordResponse> searchByKeywordAsync(string keyword) {
            MultipleChoiceApp.Bi.Subject.searchByKeywordRequest inValue = new MultipleChoiceApp.Bi.Subject.searchByKeywordRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Subject.searchByKeywordRequestBody();
            inValue.Body.keyword = keyword;
            return ((MultipleChoiceApp.Bi.Subject.SubjectServiceSoap)(this)).searchByKeywordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Subject.getAllForSelectDataResponse MultipleChoiceApp.Bi.Subject.SubjectServiceSoap.getAllForSelectData(MultipleChoiceApp.Bi.Subject.getAllForSelectDataRequest request) {
            return base.Channel.getAllForSelectData(request);
        }
        
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Subject.Subject> getAllForSelectData() {
            MultipleChoiceApp.Bi.Subject.getAllForSelectDataRequest inValue = new MultipleChoiceApp.Bi.Subject.getAllForSelectDataRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Subject.getAllForSelectDataRequestBody();
            MultipleChoiceApp.Bi.Subject.getAllForSelectDataResponse retVal = ((MultipleChoiceApp.Bi.Subject.SubjectServiceSoap)(this)).getAllForSelectData(inValue);
            return retVal.Body.getAllForSelectDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Subject.getAllForSelectDataResponse> MultipleChoiceApp.Bi.Subject.SubjectServiceSoap.getAllForSelectDataAsync(MultipleChoiceApp.Bi.Subject.getAllForSelectDataRequest request) {
            return base.Channel.getAllForSelectDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Subject.getAllForSelectDataResponse> getAllForSelectDataAsync() {
            MultipleChoiceApp.Bi.Subject.getAllForSelectDataRequest inValue = new MultipleChoiceApp.Bi.Subject.getAllForSelectDataRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Subject.getAllForSelectDataRequestBody();
            return ((MultipleChoiceApp.Bi.Subject.SubjectServiceSoap)(this)).getAllForSelectDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Subject.getAllResponse MultipleChoiceApp.Bi.Subject.SubjectServiceSoap.getAll(MultipleChoiceApp.Bi.Subject.getAllRequest request) {
            return base.Channel.getAll(request);
        }
        
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Subject.Subject> getAll(int itemsPerPage, int currentPage) {
            MultipleChoiceApp.Bi.Subject.getAllRequest inValue = new MultipleChoiceApp.Bi.Subject.getAllRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Subject.getAllRequestBody();
            inValue.Body.itemsPerPage = itemsPerPage;
            inValue.Body.currentPage = currentPage;
            MultipleChoiceApp.Bi.Subject.getAllResponse retVal = ((MultipleChoiceApp.Bi.Subject.SubjectServiceSoap)(this)).getAll(inValue);
            return retVal.Body.getAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Subject.getAllResponse> MultipleChoiceApp.Bi.Subject.SubjectServiceSoap.getAllAsync(MultipleChoiceApp.Bi.Subject.getAllRequest request) {
            return base.Channel.getAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Subject.getAllResponse> getAllAsync(int itemsPerPage, int currentPage) {
            MultipleChoiceApp.Bi.Subject.getAllRequest inValue = new MultipleChoiceApp.Bi.Subject.getAllRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Subject.getAllRequestBody();
            inValue.Body.itemsPerPage = itemsPerPage;
            inValue.Body.currentPage = currentPage;
            return ((MultipleChoiceApp.Bi.Subject.SubjectServiceSoap)(this)).getAllAsync(inValue);
        }
        
        public int countAll() {
            return base.Channel.countAll();
        }
        
        public System.Threading.Tasks.Task<int> countAllAsync() {
            return base.Channel.countAllAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Subject.getDetailsByIdResponse MultipleChoiceApp.Bi.Subject.SubjectServiceSoap.getDetailsById(MultipleChoiceApp.Bi.Subject.getDetailsByIdRequest request) {
            return base.Channel.getDetailsById(request);
        }
        
        public MultipleChoiceApp.Bi.Subject.Subject getDetailsById(int id) {
            MultipleChoiceApp.Bi.Subject.getDetailsByIdRequest inValue = new MultipleChoiceApp.Bi.Subject.getDetailsByIdRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Subject.getDetailsByIdRequestBody();
            inValue.Body.id = id;
            MultipleChoiceApp.Bi.Subject.getDetailsByIdResponse retVal = ((MultipleChoiceApp.Bi.Subject.SubjectServiceSoap)(this)).getDetailsById(inValue);
            return retVal.Body.getDetailsByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Subject.getDetailsByIdResponse> MultipleChoiceApp.Bi.Subject.SubjectServiceSoap.getDetailsByIdAsync(MultipleChoiceApp.Bi.Subject.getDetailsByIdRequest request) {
            return base.Channel.getDetailsByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Subject.getDetailsByIdResponse> getDetailsByIdAsync(int id) {
            MultipleChoiceApp.Bi.Subject.getDetailsByIdRequest inValue = new MultipleChoiceApp.Bi.Subject.getDetailsByIdRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Subject.getDetailsByIdRequestBody();
            inValue.Body.id = id;
            return ((MultipleChoiceApp.Bi.Subject.SubjectServiceSoap)(this)).getDetailsByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Subject.addResponse MultipleChoiceApp.Bi.Subject.SubjectServiceSoap.add(MultipleChoiceApp.Bi.Subject.addRequest request) {
            return base.Channel.add(request);
        }
        
        public bool add(MultipleChoiceApp.Bi.Subject.Subject item) {
            MultipleChoiceApp.Bi.Subject.addRequest inValue = new MultipleChoiceApp.Bi.Subject.addRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Subject.addRequestBody();
            inValue.Body.item = item;
            MultipleChoiceApp.Bi.Subject.addResponse retVal = ((MultipleChoiceApp.Bi.Subject.SubjectServiceSoap)(this)).add(inValue);
            return retVal.Body.addResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Subject.addResponse> MultipleChoiceApp.Bi.Subject.SubjectServiceSoap.addAsync(MultipleChoiceApp.Bi.Subject.addRequest request) {
            return base.Channel.addAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Subject.addResponse> addAsync(MultipleChoiceApp.Bi.Subject.Subject item) {
            MultipleChoiceApp.Bi.Subject.addRequest inValue = new MultipleChoiceApp.Bi.Subject.addRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Subject.addRequestBody();
            inValue.Body.item = item;
            return ((MultipleChoiceApp.Bi.Subject.SubjectServiceSoap)(this)).addAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Subject.addManyResponse MultipleChoiceApp.Bi.Subject.SubjectServiceSoap.addMany(MultipleChoiceApp.Bi.Subject.addManyRequest request) {
            return base.Channel.addMany(request);
        }
        
        public int addMany(System.Collections.Generic.List<MultipleChoiceApp.Bi.Subject.Subject> list) {
            MultipleChoiceApp.Bi.Subject.addManyRequest inValue = new MultipleChoiceApp.Bi.Subject.addManyRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Subject.addManyRequestBody();
            inValue.Body.list = list;
            MultipleChoiceApp.Bi.Subject.addManyResponse retVal = ((MultipleChoiceApp.Bi.Subject.SubjectServiceSoap)(this)).addMany(inValue);
            return retVal.Body.addManyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Subject.addManyResponse> MultipleChoiceApp.Bi.Subject.SubjectServiceSoap.addManyAsync(MultipleChoiceApp.Bi.Subject.addManyRequest request) {
            return base.Channel.addManyAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Subject.addManyResponse> addManyAsync(System.Collections.Generic.List<MultipleChoiceApp.Bi.Subject.Subject> list) {
            MultipleChoiceApp.Bi.Subject.addManyRequest inValue = new MultipleChoiceApp.Bi.Subject.addManyRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Subject.addManyRequestBody();
            inValue.Body.list = list;
            return ((MultipleChoiceApp.Bi.Subject.SubjectServiceSoap)(this)).addManyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Subject.updateResponse MultipleChoiceApp.Bi.Subject.SubjectServiceSoap.update(MultipleChoiceApp.Bi.Subject.updateRequest request) {
            return base.Channel.update(request);
        }
        
        public bool update(MultipleChoiceApp.Bi.Subject.Subject item) {
            MultipleChoiceApp.Bi.Subject.updateRequest inValue = new MultipleChoiceApp.Bi.Subject.updateRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Subject.updateRequestBody();
            inValue.Body.item = item;
            MultipleChoiceApp.Bi.Subject.updateResponse retVal = ((MultipleChoiceApp.Bi.Subject.SubjectServiceSoap)(this)).update(inValue);
            return retVal.Body.updateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Subject.updateResponse> MultipleChoiceApp.Bi.Subject.SubjectServiceSoap.updateAsync(MultipleChoiceApp.Bi.Subject.updateRequest request) {
            return base.Channel.updateAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Subject.updateResponse> updateAsync(MultipleChoiceApp.Bi.Subject.Subject item) {
            MultipleChoiceApp.Bi.Subject.updateRequest inValue = new MultipleChoiceApp.Bi.Subject.updateRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Subject.updateRequestBody();
            inValue.Body.item = item;
            return ((MultipleChoiceApp.Bi.Subject.SubjectServiceSoap)(this)).updateAsync(inValue);
        }
        
        public bool delete(int id) {
            return base.Channel.delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> deleteAsync(int id) {
            return base.Channel.deleteAsync(id);
        }
    }
}
