//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultipleChoiceApp.Bi.Question {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Question", Namespace="http://peteranh.com/Services/Question")]
    [System.SerializableAttribute()]
    public partial class Question : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        private int SubjectIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LevelField;
        
        private int ChapterField;
        
        private int CorrectAnswerNoField;
        
        private System.DateTime CreatedAtField;
        
        private int CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LecturerField;
        
        private int QuestionInExamCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<MultipleChoiceApp.Bi.Question.Answer> AnswersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int SubjectId {
            get {
                return this.SubjectIdField;
            }
            set {
                if ((this.SubjectIdField.Equals(value) != true)) {
                    this.SubjectIdField = value;
                    this.RaisePropertyChanged("SubjectId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SubjectCode {
            get {
                return this.SubjectCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectCodeField, value) != true)) {
                    this.SubjectCodeField = value;
                    this.RaisePropertyChanged("SubjectCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Level {
            get {
                return this.LevelField;
            }
            set {
                if ((object.ReferenceEquals(this.LevelField, value) != true)) {
                    this.LevelField = value;
                    this.RaisePropertyChanged("Level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Chapter {
            get {
                return this.ChapterField;
            }
            set {
                if ((this.ChapterField.Equals(value) != true)) {
                    this.ChapterField = value;
                    this.RaisePropertyChanged("Chapter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int CorrectAnswerNo {
            get {
                return this.CorrectAnswerNoField;
            }
            set {
                if ((this.CorrectAnswerNoField.Equals(value) != true)) {
                    this.CorrectAnswerNoField = value;
                    this.RaisePropertyChanged("CorrectAnswerNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime CreatedAt {
            get {
                return this.CreatedAtField;
            }
            set {
                if ((this.CreatedAtField.Equals(value) != true)) {
                    this.CreatedAtField = value;
                    this.RaisePropertyChanged("CreatedAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((this.CreatedByField.Equals(value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Lecturer {
            get {
                return this.LecturerField;
            }
            set {
                if ((object.ReferenceEquals(this.LecturerField, value) != true)) {
                    this.LecturerField = value;
                    this.RaisePropertyChanged("Lecturer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int QuestionInExamCount {
            get {
                return this.QuestionInExamCountField;
            }
            set {
                if ((this.QuestionInExamCountField.Equals(value) != true)) {
                    this.QuestionInExamCountField = value;
                    this.RaisePropertyChanged("QuestionInExamCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Question.Answer> Answers {
            get {
                return this.AnswersField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswersField, value) != true)) {
                    this.AnswersField = value;
                    this.RaisePropertyChanged("Answers");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Answer", Namespace="http://peteranh.com/Services/Question")]
    [System.SerializableAttribute()]
    public partial class Answer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int QuestionIdField;
        
        private int NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        private int AnswerCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int QuestionId {
            get {
                return this.QuestionIdField;
            }
            set {
                if ((this.QuestionIdField.Equals(value) != true)) {
                    this.QuestionIdField = value;
                    this.RaisePropertyChanged("QuestionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int No {
            get {
                return this.NoField;
            }
            set {
                if ((this.NoField.Equals(value) != true)) {
                    this.NoField = value;
                    this.RaisePropertyChanged("No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int AnswerCount {
            get {
                return this.AnswerCountField;
            }
            set {
                if ((this.AnswerCountField.Equals(value) != true)) {
                    this.AnswerCountField = value;
                    this.RaisePropertyChanged("AnswerCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://peteranh.com/Services/Question", ConfigurationName="Bi.Question.QuestionServiceSoap")]
    public interface QuestionServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Question/countBySubjectId", ReplyAction="*")]
        int countBySubjectId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Question/countBySubjectId", ReplyAction="*")]
        System.Threading.Tasks.Task<int> countBySubjectIdAsync(int id);
        
        // CODEGEN: Generating message contract since element name getAllWithAnswerCountByExamIdResult from namespace http://peteranh.com/Services/Question is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Question/getAllWithAnswerCountByExamId", ReplyAction="*")]
        MultipleChoiceApp.Bi.Question.getAllWithAnswerCountByExamIdResponse getAllWithAnswerCountByExamId(MultipleChoiceApp.Bi.Question.getAllWithAnswerCountByExamIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Question/getAllWithAnswerCountByExamId", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Question.getAllWithAnswerCountByExamIdResponse> getAllWithAnswerCountByExamIdAsync(MultipleChoiceApp.Bi.Question.getAllWithAnswerCountByExamIdRequest request);
        
        // CODEGEN: Generating message contract since element name level from namespace http://peteranh.com/Services/Question is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Question/getRandomByLevel", ReplyAction="*")]
        MultipleChoiceApp.Bi.Question.getRandomByLevelResponse getRandomByLevel(MultipleChoiceApp.Bi.Question.getRandomByLevelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Question/getRandomByLevel", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Question.getRandomByLevelResponse> getRandomByLevelAsync(MultipleChoiceApp.Bi.Question.getRandomByLevelRequest request);
        
        // CODEGEN: Generating message contract since element name getAllBySubjectIdResult from namespace http://peteranh.com/Services/Question is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Question/getAllBySubjectId", ReplyAction="*")]
        MultipleChoiceApp.Bi.Question.getAllBySubjectIdResponse getAllBySubjectId(MultipleChoiceApp.Bi.Question.getAllBySubjectIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Question/getAllBySubjectId", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Question.getAllBySubjectIdResponse> getAllBySubjectIdAsync(MultipleChoiceApp.Bi.Question.getAllBySubjectIdRequest request);
        
        // CODEGEN: Generating message contract since element name getAllWithAnswersBySubjectIdResult from namespace http://peteranh.com/Services/Question is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Question/getAllWithAnswersBySubjectId", ReplyAction="*")]
        MultipleChoiceApp.Bi.Question.getAllWithAnswersBySubjectIdResponse getAllWithAnswersBySubjectId(MultipleChoiceApp.Bi.Question.getAllWithAnswersBySubjectIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Question/getAllWithAnswersBySubjectId", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Question.getAllWithAnswersBySubjectIdResponse> getAllWithAnswersBySubjectIdAsync(MultipleChoiceApp.Bi.Question.getAllWithAnswersBySubjectIdRequest request);
        
        // CODEGEN: Generating message contract since element name keyword from namespace http://peteranh.com/Services/Question is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Question/searchByKeyword", ReplyAction="*")]
        MultipleChoiceApp.Bi.Question.searchByKeywordResponse searchByKeyword(MultipleChoiceApp.Bi.Question.searchByKeywordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Question/searchByKeyword", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Question.searchByKeywordResponse> searchByKeywordAsync(MultipleChoiceApp.Bi.Question.searchByKeywordRequest request);
        
        // CODEGEN: Generating message contract since element name getDetailsByIdResult from namespace http://peteranh.com/Services/Question is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Question/getDetailsById", ReplyAction="*")]
        MultipleChoiceApp.Bi.Question.getDetailsByIdResponse getDetailsById(MultipleChoiceApp.Bi.Question.getDetailsByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Question/getDetailsById", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Question.getDetailsByIdResponse> getDetailsByIdAsync(MultipleChoiceApp.Bi.Question.getDetailsByIdRequest request);
        
        // CODEGEN: Generating message contract since element name item from namespace http://peteranh.com/Services/Question is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Question/add", ReplyAction="*")]
        MultipleChoiceApp.Bi.Question.addResponse add(MultipleChoiceApp.Bi.Question.addRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Question/add", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Question.addResponse> addAsync(MultipleChoiceApp.Bi.Question.addRequest request);
        
        // CODEGEN: Generating message contract since element name list from namespace http://peteranh.com/Services/Question is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Question/addMany", ReplyAction="*")]
        MultipleChoiceApp.Bi.Question.addManyResponse addMany(MultipleChoiceApp.Bi.Question.addManyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Question/addMany", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Question.addManyResponse> addManyAsync(MultipleChoiceApp.Bi.Question.addManyRequest request);
        
        // CODEGEN: Generating message contract since element name item from namespace http://peteranh.com/Services/Question is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Question/update", ReplyAction="*")]
        MultipleChoiceApp.Bi.Question.updateResponse update(MultipleChoiceApp.Bi.Question.updateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Question/update", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Question.updateResponse> updateAsync(MultipleChoiceApp.Bi.Question.updateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Question/delete", ReplyAction="*")]
        bool delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Question/delete", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> deleteAsync(int id);
        
        // CODEGEN: Generating message contract since element name getAllForSelectDataResult from namespace http://peteranh.com/Services/Question is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Question/getAllForSelectData", ReplyAction="*")]
        MultipleChoiceApp.Bi.Question.getAllForSelectDataResponse getAllForSelectData(MultipleChoiceApp.Bi.Question.getAllForSelectDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Question/getAllForSelectData", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Question.getAllForSelectDataResponse> getAllForSelectDataAsync(MultipleChoiceApp.Bi.Question.getAllForSelectDataRequest request);
        
        // CODEGEN: Generating message contract since element name getAllResult from namespace http://peteranh.com/Services/Question is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Question/getAll", ReplyAction="*")]
        MultipleChoiceApp.Bi.Question.getAllResponse getAll(MultipleChoiceApp.Bi.Question.getAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Question/getAll", ReplyAction="*")]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Question.getAllResponse> getAllAsync(MultipleChoiceApp.Bi.Question.getAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Question/countAll", ReplyAction="*")]
        int countAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peteranh.com/Services/Question/countAll", ReplyAction="*")]
        System.Threading.Tasks.Task<int> countAllAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllWithAnswerCountByExamIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllWithAnswerCountByExamId", Namespace="http://peteranh.com/Services/Question", Order=0)]
        public MultipleChoiceApp.Bi.Question.getAllWithAnswerCountByExamIdRequestBody Body;
        
        public getAllWithAnswerCountByExamIdRequest() {
        }
        
        public getAllWithAnswerCountByExamIdRequest(MultipleChoiceApp.Bi.Question.getAllWithAnswerCountByExamIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Question")]
    public partial class getAllWithAnswerCountByExamIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public getAllWithAnswerCountByExamIdRequestBody() {
        }
        
        public getAllWithAnswerCountByExamIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllWithAnswerCountByExamIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllWithAnswerCountByExamIdResponse", Namespace="http://peteranh.com/Services/Question", Order=0)]
        public MultipleChoiceApp.Bi.Question.getAllWithAnswerCountByExamIdResponseBody Body;
        
        public getAllWithAnswerCountByExamIdResponse() {
        }
        
        public getAllWithAnswerCountByExamIdResponse(MultipleChoiceApp.Bi.Question.getAllWithAnswerCountByExamIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Question")]
    public partial class getAllWithAnswerCountByExamIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Question.Question> getAllWithAnswerCountByExamIdResult;
        
        public getAllWithAnswerCountByExamIdResponseBody() {
        }
        
        public getAllWithAnswerCountByExamIdResponseBody(System.Collections.Generic.List<MultipleChoiceApp.Bi.Question.Question> getAllWithAnswerCountByExamIdResult) {
            this.getAllWithAnswerCountByExamIdResult = getAllWithAnswerCountByExamIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRandomByLevelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRandomByLevel", Namespace="http://peteranh.com/Services/Question", Order=0)]
        public MultipleChoiceApp.Bi.Question.getRandomByLevelRequestBody Body;
        
        public getRandomByLevelRequest() {
        }
        
        public getRandomByLevelRequest(MultipleChoiceApp.Bi.Question.getRandomByLevelRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Question")]
    public partial class getRandomByLevelRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int subjectId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string level;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int qty;
        
        public getRandomByLevelRequestBody() {
        }
        
        public getRandomByLevelRequestBody(int subjectId, string level, int qty) {
            this.subjectId = subjectId;
            this.level = level;
            this.qty = qty;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRandomByLevelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRandomByLevelResponse", Namespace="http://peteranh.com/Services/Question", Order=0)]
        public MultipleChoiceApp.Bi.Question.getRandomByLevelResponseBody Body;
        
        public getRandomByLevelResponse() {
        }
        
        public getRandomByLevelResponse(MultipleChoiceApp.Bi.Question.getRandomByLevelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Question")]
    public partial class getRandomByLevelResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Question.Question> getRandomByLevelResult;
        
        public getRandomByLevelResponseBody() {
        }
        
        public getRandomByLevelResponseBody(System.Collections.Generic.List<MultipleChoiceApp.Bi.Question.Question> getRandomByLevelResult) {
            this.getRandomByLevelResult = getRandomByLevelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllBySubjectIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllBySubjectId", Namespace="http://peteranh.com/Services/Question", Order=0)]
        public MultipleChoiceApp.Bi.Question.getAllBySubjectIdRequestBody Body;
        
        public getAllBySubjectIdRequest() {
        }
        
        public getAllBySubjectIdRequest(MultipleChoiceApp.Bi.Question.getAllBySubjectIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Question")]
    public partial class getAllBySubjectIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int itemsPerPage;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int currentPage;
        
        public getAllBySubjectIdRequestBody() {
        }
        
        public getAllBySubjectIdRequestBody(int id, int itemsPerPage, int currentPage) {
            this.id = id;
            this.itemsPerPage = itemsPerPage;
            this.currentPage = currentPage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllBySubjectIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllBySubjectIdResponse", Namespace="http://peteranh.com/Services/Question", Order=0)]
        public MultipleChoiceApp.Bi.Question.getAllBySubjectIdResponseBody Body;
        
        public getAllBySubjectIdResponse() {
        }
        
        public getAllBySubjectIdResponse(MultipleChoiceApp.Bi.Question.getAllBySubjectIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Question")]
    public partial class getAllBySubjectIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Question.Question> getAllBySubjectIdResult;
        
        public getAllBySubjectIdResponseBody() {
        }
        
        public getAllBySubjectIdResponseBody(System.Collections.Generic.List<MultipleChoiceApp.Bi.Question.Question> getAllBySubjectIdResult) {
            this.getAllBySubjectIdResult = getAllBySubjectIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllWithAnswersBySubjectIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllWithAnswersBySubjectId", Namespace="http://peteranh.com/Services/Question", Order=0)]
        public MultipleChoiceApp.Bi.Question.getAllWithAnswersBySubjectIdRequestBody Body;
        
        public getAllWithAnswersBySubjectIdRequest() {
        }
        
        public getAllWithAnswersBySubjectIdRequest(MultipleChoiceApp.Bi.Question.getAllWithAnswersBySubjectIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Question")]
    public partial class getAllWithAnswersBySubjectIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public getAllWithAnswersBySubjectIdRequestBody() {
        }
        
        public getAllWithAnswersBySubjectIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllWithAnswersBySubjectIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllWithAnswersBySubjectIdResponse", Namespace="http://peteranh.com/Services/Question", Order=0)]
        public MultipleChoiceApp.Bi.Question.getAllWithAnswersBySubjectIdResponseBody Body;
        
        public getAllWithAnswersBySubjectIdResponse() {
        }
        
        public getAllWithAnswersBySubjectIdResponse(MultipleChoiceApp.Bi.Question.getAllWithAnswersBySubjectIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Question")]
    public partial class getAllWithAnswersBySubjectIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Question.Question> getAllWithAnswersBySubjectIdResult;
        
        public getAllWithAnswersBySubjectIdResponseBody() {
        }
        
        public getAllWithAnswersBySubjectIdResponseBody(System.Collections.Generic.List<MultipleChoiceApp.Bi.Question.Question> getAllWithAnswersBySubjectIdResult) {
            this.getAllWithAnswersBySubjectIdResult = getAllWithAnswersBySubjectIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchByKeywordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchByKeyword", Namespace="http://peteranh.com/Services/Question", Order=0)]
        public MultipleChoiceApp.Bi.Question.searchByKeywordRequestBody Body;
        
        public searchByKeywordRequest() {
        }
        
        public searchByKeywordRequest(MultipleChoiceApp.Bi.Question.searchByKeywordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Question")]
    public partial class searchByKeywordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string keyword;
        
        public searchByKeywordRequestBody() {
        }
        
        public searchByKeywordRequestBody(int id, string keyword) {
            this.id = id;
            this.keyword = keyword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchByKeywordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchByKeywordResponse", Namespace="http://peteranh.com/Services/Question", Order=0)]
        public MultipleChoiceApp.Bi.Question.searchByKeywordResponseBody Body;
        
        public searchByKeywordResponse() {
        }
        
        public searchByKeywordResponse(MultipleChoiceApp.Bi.Question.searchByKeywordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Question")]
    public partial class searchByKeywordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Question.Question> searchByKeywordResult;
        
        public searchByKeywordResponseBody() {
        }
        
        public searchByKeywordResponseBody(System.Collections.Generic.List<MultipleChoiceApp.Bi.Question.Question> searchByKeywordResult) {
            this.searchByKeywordResult = searchByKeywordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDetailsByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDetailsById", Namespace="http://peteranh.com/Services/Question", Order=0)]
        public MultipleChoiceApp.Bi.Question.getDetailsByIdRequestBody Body;
        
        public getDetailsByIdRequest() {
        }
        
        public getDetailsByIdRequest(MultipleChoiceApp.Bi.Question.getDetailsByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Question")]
    public partial class getDetailsByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public getDetailsByIdRequestBody() {
        }
        
        public getDetailsByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDetailsByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDetailsByIdResponse", Namespace="http://peteranh.com/Services/Question", Order=0)]
        public MultipleChoiceApp.Bi.Question.getDetailsByIdResponseBody Body;
        
        public getDetailsByIdResponse() {
        }
        
        public getDetailsByIdResponse(MultipleChoiceApp.Bi.Question.getDetailsByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Question")]
    public partial class getDetailsByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MultipleChoiceApp.Bi.Question.Question getDetailsByIdResult;
        
        public getDetailsByIdResponseBody() {
        }
        
        public getDetailsByIdResponseBody(MultipleChoiceApp.Bi.Question.Question getDetailsByIdResult) {
            this.getDetailsByIdResult = getDetailsByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="add", Namespace="http://peteranh.com/Services/Question", Order=0)]
        public MultipleChoiceApp.Bi.Question.addRequestBody Body;
        
        public addRequest() {
        }
        
        public addRequest(MultipleChoiceApp.Bi.Question.addRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Question")]
    public partial class addRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MultipleChoiceApp.Bi.Question.Question item;
        
        public addRequestBody() {
        }
        
        public addRequestBody(MultipleChoiceApp.Bi.Question.Question item) {
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addResponse", Namespace="http://peteranh.com/Services/Question", Order=0)]
        public MultipleChoiceApp.Bi.Question.addResponseBody Body;
        
        public addResponse() {
        }
        
        public addResponse(MultipleChoiceApp.Bi.Question.addResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Question")]
    public partial class addResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool addResult;
        
        public addResponseBody() {
        }
        
        public addResponseBody(bool addResult) {
            this.addResult = addResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addManyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addMany", Namespace="http://peteranh.com/Services/Question", Order=0)]
        public MultipleChoiceApp.Bi.Question.addManyRequestBody Body;
        
        public addManyRequest() {
        }
        
        public addManyRequest(MultipleChoiceApp.Bi.Question.addManyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Question")]
    public partial class addManyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Question.Question> list;
        
        public addManyRequestBody() {
        }
        
        public addManyRequestBody(System.Collections.Generic.List<MultipleChoiceApp.Bi.Question.Question> list) {
            this.list = list;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addManyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addManyResponse", Namespace="http://peteranh.com/Services/Question", Order=0)]
        public MultipleChoiceApp.Bi.Question.addManyResponseBody Body;
        
        public addManyResponse() {
        }
        
        public addManyResponse(MultipleChoiceApp.Bi.Question.addManyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Question")]
    public partial class addManyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int addManyResult;
        
        public addManyResponseBody() {
        }
        
        public addManyResponseBody(int addManyResult) {
            this.addManyResult = addManyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="update", Namespace="http://peteranh.com/Services/Question", Order=0)]
        public MultipleChoiceApp.Bi.Question.updateRequestBody Body;
        
        public updateRequest() {
        }
        
        public updateRequest(MultipleChoiceApp.Bi.Question.updateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Question")]
    public partial class updateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MultipleChoiceApp.Bi.Question.Question item;
        
        public updateRequestBody() {
        }
        
        public updateRequestBody(MultipleChoiceApp.Bi.Question.Question item) {
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateResponse", Namespace="http://peteranh.com/Services/Question", Order=0)]
        public MultipleChoiceApp.Bi.Question.updateResponseBody Body;
        
        public updateResponse() {
        }
        
        public updateResponse(MultipleChoiceApp.Bi.Question.updateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Question")]
    public partial class updateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool updateResult;
        
        public updateResponseBody() {
        }
        
        public updateResponseBody(bool updateResult) {
            this.updateResult = updateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllForSelectDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllForSelectData", Namespace="http://peteranh.com/Services/Question", Order=0)]
        public MultipleChoiceApp.Bi.Question.getAllForSelectDataRequestBody Body;
        
        public getAllForSelectDataRequest() {
        }
        
        public getAllForSelectDataRequest(MultipleChoiceApp.Bi.Question.getAllForSelectDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getAllForSelectDataRequestBody {
        
        public getAllForSelectDataRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllForSelectDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllForSelectDataResponse", Namespace="http://peteranh.com/Services/Question", Order=0)]
        public MultipleChoiceApp.Bi.Question.getAllForSelectDataResponseBody Body;
        
        public getAllForSelectDataResponse() {
        }
        
        public getAllForSelectDataResponse(MultipleChoiceApp.Bi.Question.getAllForSelectDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Question")]
    public partial class getAllForSelectDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Question.Question> getAllForSelectDataResult;
        
        public getAllForSelectDataResponseBody() {
        }
        
        public getAllForSelectDataResponseBody(System.Collections.Generic.List<MultipleChoiceApp.Bi.Question.Question> getAllForSelectDataResult) {
            this.getAllForSelectDataResult = getAllForSelectDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAll", Namespace="http://peteranh.com/Services/Question", Order=0)]
        public MultipleChoiceApp.Bi.Question.getAllRequestBody Body;
        
        public getAllRequest() {
        }
        
        public getAllRequest(MultipleChoiceApp.Bi.Question.getAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Question")]
    public partial class getAllRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int itemsPerPage;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int currentPage;
        
        public getAllRequestBody() {
        }
        
        public getAllRequestBody(int itemsPerPage, int currentPage) {
            this.itemsPerPage = itemsPerPage;
            this.currentPage = currentPage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllResponse", Namespace="http://peteranh.com/Services/Question", Order=0)]
        public MultipleChoiceApp.Bi.Question.getAllResponseBody Body;
        
        public getAllResponse() {
        }
        
        public getAllResponse(MultipleChoiceApp.Bi.Question.getAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://peteranh.com/Services/Question")]
    public partial class getAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Question.Question> getAllResult;
        
        public getAllResponseBody() {
        }
        
        public getAllResponseBody(System.Collections.Generic.List<MultipleChoiceApp.Bi.Question.Question> getAllResult) {
            this.getAllResult = getAllResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QuestionServiceSoapChannel : MultipleChoiceApp.Bi.Question.QuestionServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QuestionServiceSoapClient : System.ServiceModel.ClientBase<MultipleChoiceApp.Bi.Question.QuestionServiceSoap>, MultipleChoiceApp.Bi.Question.QuestionServiceSoap {
        
        public QuestionServiceSoapClient() {
        }
        
        public QuestionServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QuestionServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuestionServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuestionServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int countBySubjectId(int id) {
            return base.Channel.countBySubjectId(id);
        }
        
        public System.Threading.Tasks.Task<int> countBySubjectIdAsync(int id) {
            return base.Channel.countBySubjectIdAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Question.getAllWithAnswerCountByExamIdResponse MultipleChoiceApp.Bi.Question.QuestionServiceSoap.getAllWithAnswerCountByExamId(MultipleChoiceApp.Bi.Question.getAllWithAnswerCountByExamIdRequest request) {
            return base.Channel.getAllWithAnswerCountByExamId(request);
        }
        
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Question.Question> getAllWithAnswerCountByExamId(int id) {
            MultipleChoiceApp.Bi.Question.getAllWithAnswerCountByExamIdRequest inValue = new MultipleChoiceApp.Bi.Question.getAllWithAnswerCountByExamIdRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Question.getAllWithAnswerCountByExamIdRequestBody();
            inValue.Body.id = id;
            MultipleChoiceApp.Bi.Question.getAllWithAnswerCountByExamIdResponse retVal = ((MultipleChoiceApp.Bi.Question.QuestionServiceSoap)(this)).getAllWithAnswerCountByExamId(inValue);
            return retVal.Body.getAllWithAnswerCountByExamIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Question.getAllWithAnswerCountByExamIdResponse> MultipleChoiceApp.Bi.Question.QuestionServiceSoap.getAllWithAnswerCountByExamIdAsync(MultipleChoiceApp.Bi.Question.getAllWithAnswerCountByExamIdRequest request) {
            return base.Channel.getAllWithAnswerCountByExamIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Question.getAllWithAnswerCountByExamIdResponse> getAllWithAnswerCountByExamIdAsync(int id) {
            MultipleChoiceApp.Bi.Question.getAllWithAnswerCountByExamIdRequest inValue = new MultipleChoiceApp.Bi.Question.getAllWithAnswerCountByExamIdRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Question.getAllWithAnswerCountByExamIdRequestBody();
            inValue.Body.id = id;
            return ((MultipleChoiceApp.Bi.Question.QuestionServiceSoap)(this)).getAllWithAnswerCountByExamIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Question.getRandomByLevelResponse MultipleChoiceApp.Bi.Question.QuestionServiceSoap.getRandomByLevel(MultipleChoiceApp.Bi.Question.getRandomByLevelRequest request) {
            return base.Channel.getRandomByLevel(request);
        }
        
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Question.Question> getRandomByLevel(int subjectId, string level, int qty) {
            MultipleChoiceApp.Bi.Question.getRandomByLevelRequest inValue = new MultipleChoiceApp.Bi.Question.getRandomByLevelRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Question.getRandomByLevelRequestBody();
            inValue.Body.subjectId = subjectId;
            inValue.Body.level = level;
            inValue.Body.qty = qty;
            MultipleChoiceApp.Bi.Question.getRandomByLevelResponse retVal = ((MultipleChoiceApp.Bi.Question.QuestionServiceSoap)(this)).getRandomByLevel(inValue);
            return retVal.Body.getRandomByLevelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Question.getRandomByLevelResponse> MultipleChoiceApp.Bi.Question.QuestionServiceSoap.getRandomByLevelAsync(MultipleChoiceApp.Bi.Question.getRandomByLevelRequest request) {
            return base.Channel.getRandomByLevelAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Question.getRandomByLevelResponse> getRandomByLevelAsync(int subjectId, string level, int qty) {
            MultipleChoiceApp.Bi.Question.getRandomByLevelRequest inValue = new MultipleChoiceApp.Bi.Question.getRandomByLevelRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Question.getRandomByLevelRequestBody();
            inValue.Body.subjectId = subjectId;
            inValue.Body.level = level;
            inValue.Body.qty = qty;
            return ((MultipleChoiceApp.Bi.Question.QuestionServiceSoap)(this)).getRandomByLevelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Question.getAllBySubjectIdResponse MultipleChoiceApp.Bi.Question.QuestionServiceSoap.getAllBySubjectId(MultipleChoiceApp.Bi.Question.getAllBySubjectIdRequest request) {
            return base.Channel.getAllBySubjectId(request);
        }
        
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Question.Question> getAllBySubjectId(int id, int itemsPerPage, int currentPage) {
            MultipleChoiceApp.Bi.Question.getAllBySubjectIdRequest inValue = new MultipleChoiceApp.Bi.Question.getAllBySubjectIdRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Question.getAllBySubjectIdRequestBody();
            inValue.Body.id = id;
            inValue.Body.itemsPerPage = itemsPerPage;
            inValue.Body.currentPage = currentPage;
            MultipleChoiceApp.Bi.Question.getAllBySubjectIdResponse retVal = ((MultipleChoiceApp.Bi.Question.QuestionServiceSoap)(this)).getAllBySubjectId(inValue);
            return retVal.Body.getAllBySubjectIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Question.getAllBySubjectIdResponse> MultipleChoiceApp.Bi.Question.QuestionServiceSoap.getAllBySubjectIdAsync(MultipleChoiceApp.Bi.Question.getAllBySubjectIdRequest request) {
            return base.Channel.getAllBySubjectIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Question.getAllBySubjectIdResponse> getAllBySubjectIdAsync(int id, int itemsPerPage, int currentPage) {
            MultipleChoiceApp.Bi.Question.getAllBySubjectIdRequest inValue = new MultipleChoiceApp.Bi.Question.getAllBySubjectIdRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Question.getAllBySubjectIdRequestBody();
            inValue.Body.id = id;
            inValue.Body.itemsPerPage = itemsPerPage;
            inValue.Body.currentPage = currentPage;
            return ((MultipleChoiceApp.Bi.Question.QuestionServiceSoap)(this)).getAllBySubjectIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Question.getAllWithAnswersBySubjectIdResponse MultipleChoiceApp.Bi.Question.QuestionServiceSoap.getAllWithAnswersBySubjectId(MultipleChoiceApp.Bi.Question.getAllWithAnswersBySubjectIdRequest request) {
            return base.Channel.getAllWithAnswersBySubjectId(request);
        }
        
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Question.Question> getAllWithAnswersBySubjectId(int id) {
            MultipleChoiceApp.Bi.Question.getAllWithAnswersBySubjectIdRequest inValue = new MultipleChoiceApp.Bi.Question.getAllWithAnswersBySubjectIdRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Question.getAllWithAnswersBySubjectIdRequestBody();
            inValue.Body.id = id;
            MultipleChoiceApp.Bi.Question.getAllWithAnswersBySubjectIdResponse retVal = ((MultipleChoiceApp.Bi.Question.QuestionServiceSoap)(this)).getAllWithAnswersBySubjectId(inValue);
            return retVal.Body.getAllWithAnswersBySubjectIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Question.getAllWithAnswersBySubjectIdResponse> MultipleChoiceApp.Bi.Question.QuestionServiceSoap.getAllWithAnswersBySubjectIdAsync(MultipleChoiceApp.Bi.Question.getAllWithAnswersBySubjectIdRequest request) {
            return base.Channel.getAllWithAnswersBySubjectIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Question.getAllWithAnswersBySubjectIdResponse> getAllWithAnswersBySubjectIdAsync(int id) {
            MultipleChoiceApp.Bi.Question.getAllWithAnswersBySubjectIdRequest inValue = new MultipleChoiceApp.Bi.Question.getAllWithAnswersBySubjectIdRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Question.getAllWithAnswersBySubjectIdRequestBody();
            inValue.Body.id = id;
            return ((MultipleChoiceApp.Bi.Question.QuestionServiceSoap)(this)).getAllWithAnswersBySubjectIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Question.searchByKeywordResponse MultipleChoiceApp.Bi.Question.QuestionServiceSoap.searchByKeyword(MultipleChoiceApp.Bi.Question.searchByKeywordRequest request) {
            return base.Channel.searchByKeyword(request);
        }
        
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Question.Question> searchByKeyword(int id, string keyword) {
            MultipleChoiceApp.Bi.Question.searchByKeywordRequest inValue = new MultipleChoiceApp.Bi.Question.searchByKeywordRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Question.searchByKeywordRequestBody();
            inValue.Body.id = id;
            inValue.Body.keyword = keyword;
            MultipleChoiceApp.Bi.Question.searchByKeywordResponse retVal = ((MultipleChoiceApp.Bi.Question.QuestionServiceSoap)(this)).searchByKeyword(inValue);
            return retVal.Body.searchByKeywordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Question.searchByKeywordResponse> MultipleChoiceApp.Bi.Question.QuestionServiceSoap.searchByKeywordAsync(MultipleChoiceApp.Bi.Question.searchByKeywordRequest request) {
            return base.Channel.searchByKeywordAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Question.searchByKeywordResponse> searchByKeywordAsync(int id, string keyword) {
            MultipleChoiceApp.Bi.Question.searchByKeywordRequest inValue = new MultipleChoiceApp.Bi.Question.searchByKeywordRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Question.searchByKeywordRequestBody();
            inValue.Body.id = id;
            inValue.Body.keyword = keyword;
            return ((MultipleChoiceApp.Bi.Question.QuestionServiceSoap)(this)).searchByKeywordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Question.getDetailsByIdResponse MultipleChoiceApp.Bi.Question.QuestionServiceSoap.getDetailsById(MultipleChoiceApp.Bi.Question.getDetailsByIdRequest request) {
            return base.Channel.getDetailsById(request);
        }
        
        public MultipleChoiceApp.Bi.Question.Question getDetailsById(int id) {
            MultipleChoiceApp.Bi.Question.getDetailsByIdRequest inValue = new MultipleChoiceApp.Bi.Question.getDetailsByIdRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Question.getDetailsByIdRequestBody();
            inValue.Body.id = id;
            MultipleChoiceApp.Bi.Question.getDetailsByIdResponse retVal = ((MultipleChoiceApp.Bi.Question.QuestionServiceSoap)(this)).getDetailsById(inValue);
            return retVal.Body.getDetailsByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Question.getDetailsByIdResponse> MultipleChoiceApp.Bi.Question.QuestionServiceSoap.getDetailsByIdAsync(MultipleChoiceApp.Bi.Question.getDetailsByIdRequest request) {
            return base.Channel.getDetailsByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Question.getDetailsByIdResponse> getDetailsByIdAsync(int id) {
            MultipleChoiceApp.Bi.Question.getDetailsByIdRequest inValue = new MultipleChoiceApp.Bi.Question.getDetailsByIdRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Question.getDetailsByIdRequestBody();
            inValue.Body.id = id;
            return ((MultipleChoiceApp.Bi.Question.QuestionServiceSoap)(this)).getDetailsByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Question.addResponse MultipleChoiceApp.Bi.Question.QuestionServiceSoap.add(MultipleChoiceApp.Bi.Question.addRequest request) {
            return base.Channel.add(request);
        }
        
        public bool add(MultipleChoiceApp.Bi.Question.Question item) {
            MultipleChoiceApp.Bi.Question.addRequest inValue = new MultipleChoiceApp.Bi.Question.addRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Question.addRequestBody();
            inValue.Body.item = item;
            MultipleChoiceApp.Bi.Question.addResponse retVal = ((MultipleChoiceApp.Bi.Question.QuestionServiceSoap)(this)).add(inValue);
            return retVal.Body.addResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Question.addResponse> MultipleChoiceApp.Bi.Question.QuestionServiceSoap.addAsync(MultipleChoiceApp.Bi.Question.addRequest request) {
            return base.Channel.addAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Question.addResponse> addAsync(MultipleChoiceApp.Bi.Question.Question item) {
            MultipleChoiceApp.Bi.Question.addRequest inValue = new MultipleChoiceApp.Bi.Question.addRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Question.addRequestBody();
            inValue.Body.item = item;
            return ((MultipleChoiceApp.Bi.Question.QuestionServiceSoap)(this)).addAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Question.addManyResponse MultipleChoiceApp.Bi.Question.QuestionServiceSoap.addMany(MultipleChoiceApp.Bi.Question.addManyRequest request) {
            return base.Channel.addMany(request);
        }
        
        public int addMany(System.Collections.Generic.List<MultipleChoiceApp.Bi.Question.Question> list) {
            MultipleChoiceApp.Bi.Question.addManyRequest inValue = new MultipleChoiceApp.Bi.Question.addManyRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Question.addManyRequestBody();
            inValue.Body.list = list;
            MultipleChoiceApp.Bi.Question.addManyResponse retVal = ((MultipleChoiceApp.Bi.Question.QuestionServiceSoap)(this)).addMany(inValue);
            return retVal.Body.addManyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Question.addManyResponse> MultipleChoiceApp.Bi.Question.QuestionServiceSoap.addManyAsync(MultipleChoiceApp.Bi.Question.addManyRequest request) {
            return base.Channel.addManyAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Question.addManyResponse> addManyAsync(System.Collections.Generic.List<MultipleChoiceApp.Bi.Question.Question> list) {
            MultipleChoiceApp.Bi.Question.addManyRequest inValue = new MultipleChoiceApp.Bi.Question.addManyRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Question.addManyRequestBody();
            inValue.Body.list = list;
            return ((MultipleChoiceApp.Bi.Question.QuestionServiceSoap)(this)).addManyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Question.updateResponse MultipleChoiceApp.Bi.Question.QuestionServiceSoap.update(MultipleChoiceApp.Bi.Question.updateRequest request) {
            return base.Channel.update(request);
        }
        
        public bool update(MultipleChoiceApp.Bi.Question.Question item) {
            MultipleChoiceApp.Bi.Question.updateRequest inValue = new MultipleChoiceApp.Bi.Question.updateRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Question.updateRequestBody();
            inValue.Body.item = item;
            MultipleChoiceApp.Bi.Question.updateResponse retVal = ((MultipleChoiceApp.Bi.Question.QuestionServiceSoap)(this)).update(inValue);
            return retVal.Body.updateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Question.updateResponse> MultipleChoiceApp.Bi.Question.QuestionServiceSoap.updateAsync(MultipleChoiceApp.Bi.Question.updateRequest request) {
            return base.Channel.updateAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Question.updateResponse> updateAsync(MultipleChoiceApp.Bi.Question.Question item) {
            MultipleChoiceApp.Bi.Question.updateRequest inValue = new MultipleChoiceApp.Bi.Question.updateRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Question.updateRequestBody();
            inValue.Body.item = item;
            return ((MultipleChoiceApp.Bi.Question.QuestionServiceSoap)(this)).updateAsync(inValue);
        }
        
        public bool delete(int id) {
            return base.Channel.delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> deleteAsync(int id) {
            return base.Channel.deleteAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Question.getAllForSelectDataResponse MultipleChoiceApp.Bi.Question.QuestionServiceSoap.getAllForSelectData(MultipleChoiceApp.Bi.Question.getAllForSelectDataRequest request) {
            return base.Channel.getAllForSelectData(request);
        }
        
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Question.Question> getAllForSelectData() {
            MultipleChoiceApp.Bi.Question.getAllForSelectDataRequest inValue = new MultipleChoiceApp.Bi.Question.getAllForSelectDataRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Question.getAllForSelectDataRequestBody();
            MultipleChoiceApp.Bi.Question.getAllForSelectDataResponse retVal = ((MultipleChoiceApp.Bi.Question.QuestionServiceSoap)(this)).getAllForSelectData(inValue);
            return retVal.Body.getAllForSelectDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Question.getAllForSelectDataResponse> MultipleChoiceApp.Bi.Question.QuestionServiceSoap.getAllForSelectDataAsync(MultipleChoiceApp.Bi.Question.getAllForSelectDataRequest request) {
            return base.Channel.getAllForSelectDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Question.getAllForSelectDataResponse> getAllForSelectDataAsync() {
            MultipleChoiceApp.Bi.Question.getAllForSelectDataRequest inValue = new MultipleChoiceApp.Bi.Question.getAllForSelectDataRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Question.getAllForSelectDataRequestBody();
            return ((MultipleChoiceApp.Bi.Question.QuestionServiceSoap)(this)).getAllForSelectDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultipleChoiceApp.Bi.Question.getAllResponse MultipleChoiceApp.Bi.Question.QuestionServiceSoap.getAll(MultipleChoiceApp.Bi.Question.getAllRequest request) {
            return base.Channel.getAll(request);
        }
        
        public System.Collections.Generic.List<MultipleChoiceApp.Bi.Question.Question> getAll(int itemsPerPage, int currentPage) {
            MultipleChoiceApp.Bi.Question.getAllRequest inValue = new MultipleChoiceApp.Bi.Question.getAllRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Question.getAllRequestBody();
            inValue.Body.itemsPerPage = itemsPerPage;
            inValue.Body.currentPage = currentPage;
            MultipleChoiceApp.Bi.Question.getAllResponse retVal = ((MultipleChoiceApp.Bi.Question.QuestionServiceSoap)(this)).getAll(inValue);
            return retVal.Body.getAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Question.getAllResponse> MultipleChoiceApp.Bi.Question.QuestionServiceSoap.getAllAsync(MultipleChoiceApp.Bi.Question.getAllRequest request) {
            return base.Channel.getAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultipleChoiceApp.Bi.Question.getAllResponse> getAllAsync(int itemsPerPage, int currentPage) {
            MultipleChoiceApp.Bi.Question.getAllRequest inValue = new MultipleChoiceApp.Bi.Question.getAllRequest();
            inValue.Body = new MultipleChoiceApp.Bi.Question.getAllRequestBody();
            inValue.Body.itemsPerPage = itemsPerPage;
            inValue.Body.currentPage = currentPage;
            return ((MultipleChoiceApp.Bi.Question.QuestionServiceSoap)(this)).getAllAsync(inValue);
        }
        
        public int countAll() {
            return base.Channel.countAll();
        }
        
        public System.Threading.Tasks.Task<int> countAllAsync() {
            return base.Channel.countAllAsync();
        }
    }
}
